### ISSUE TITLE
Method messageSender(java.lang.String) cannot be found

### ISSUE THREAD

**Issue by waytoharish** [GoogleCloudPlatform/spring-cloud-gcp#1181]
Hi Team,
I am trying to use Spring integrated to Publish a message to GCP topic but i am getting below error
Method call: Method messageSender(java.lang.String) cannot be found

My Configuration Code is like-

Gateway
public interface PubsubOutboundGateway {
void sendToPubsub(String text);
}

Service Activator
https://github.com/component
public class GspConfig {

public MessageHandler messageSender(PubSubTemplate pubsubTemplate) {
return new PubSubMessageHandler(pubsubTemplate, "myTopic");
}
}

XML Config-

<int:channel id="myInputChannel"></int:channel>

<int:service-activator
        input-channel="myInputChannel"
        ref="gspConfig"/>

<int:gateway
        service-interface="com.hksharma.config.PubsubOutboundGateway"
        default-request-channel="myInputChannel">
    <int:method name="sendToPubsub"/>
</int:gateway>
I am invoking the same in the Controller class like-
@Autowired
private PubsubOutboundGateway messagingGateway;

 messagingGateway.sendToPubsub("Test");
Please can you suggest me what wrong i am doing .

**Comment by elefeint** [comment]
It seems like a mismatch between XML configuration and Java-based configuration. `GspConfig` is a configuration class, and yet it's described as a service activator in the XML configuration. The service activator is being invoked with a `String` payload, but `messageSender()` does not accept this type of parameter. 

It's unusual to see XML configuration and Java configuration together. For Spring Boot applications, Java configuration alone is far more common. 

You are going to have an easier time if you start with [existing working sample applications](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample), and then add custom functionality as needed.

**Comment by waytoharish** [comment]
Thanks @elefeint .

I am able to do with Java annotation but requirement is to define and use it with the XML.


I am struggling with the xml configuration where messageSender expect  pubsubTemplate but i am not able to figure out how to map that in XML-

<int:service-activator
input-channel="myInputChannel"
ref="gspConfig"/>


public class GspConfig {
   public MessageHandler messageSender(PubSubTemplate pubsubTemplate) {
        return new PubSubMessageHandler(pubsubTemplate, "myTopic");
    }



}

**Comment by elefeint** [comment]
If you are using XML config, the class `GspConfig` is not needed; you can define the bean of type `PubSubMessageHandler` in the XML config directly. Note that if you are not using autoconfiguration, you'll also have to set up XML wiring to create `PubSubTemplate`, replicating all of the [autoconfiguration](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/ed87b89b72826fb1dad5bb87f7c12edbb3ccc1bf/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/pubsub/GcpPubSubAutoConfiguration.java#L205) that results in `PubSubTemplate`.

Take a look at the "XML" tabs in [Spring Integration outbound channel adapter documentation](https://docs.spring.io/spring-integration/docs/current/reference/html/core.html#channel-adapter-namespace-outbound) for how to connect the `MessageHandler` bean to the channel.

**Comment by waytoharish** [comment]
Thanks @elefeint .

I tried to do the same and removed the GspConfig  from the code but still not  getting an error 

 <int:service-activator
            input-channel="myInputChannel"
            ref="pubSubHandlere">
    </int:service-activator>

    <bean id="pubSubHandlere" class="org.springframework.cloud.gcp.pubsub.integration.outbound.PubSubMessageHandler">
    <constructor-arg index="0" ref="pubsubTemplate"/>
    <constructor-arg index="1" value="myTopic"/>
    </bean>

    <bean id="pubsubTemplate" class="org.springframework.cloud.gcp.pubsub.core.PubSubTemplate"/>

**Comment by elefeint** [comment]
The same error?

**Comment by waytoharish** [comment]
This time different error-
2022-07-06 20:07:04.442  INFO 33569 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2022-07-06 20:07:04.453  INFO 33569 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-07-06 20:07:04.468 ERROR 33569 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.integration.config.ServiceActivatorFactoryBean#0' defined in class path resource [http-outbound-gateway.xml]: Cannot resolve reference to bean 'pubSubHandlere' while setting bean property 'targetObject'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pubSubHandlere' defined in class path resource [http-outbound-gateway.xml]: Cannot resolve reference to bean 'pubsubTemplate' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pubsubTemplate' defined in class path resource [http-outbound-gateway.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.gcp.pubsub.core.PubSubTemplate]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.springframework.cloud.gcp.pubsub.core.PubSubTemplate.<init>()
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:342) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:113) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1707) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1452) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:934) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.15.jar:5.3.15]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.15.jar:5.3.15]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) ~[spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:414) ~[spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302) ~[spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) ~[spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) ~[spring-boot-2.6.3.jar:2.6.3]
	at com.hksharma.App.main(App.java:12) ~[main/:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pubSubHandlere' defined in class path resource [http-outbound-gateway.xml]: Cannot resolve reference to bean 'pubsubTemplate' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pubsubTemplate' defined in class path resource [http-outbound-gateway.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.gcp.pubsub.core.PubSubTemplate]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.springframework.cloud.gcp.pubsub.core.PubSubTemplate.<init>()
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:342) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:113) ~[spring-beans-5.3.15.jar:5.3.15]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pubSubHandlere' defined in class path resource [http-outbound-gateway.xml]: Cannot resolve reference to bean 'pubsubTemplate' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pubsubTemplate' defined in class path resource [http-outbound-gateway.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.gcp.pubsub.core.PubSubTemplate]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.springframework.cloud.gcp.pubsub.core.PubSubTemplate.<init>()

	at org.springframework.beans.factory.support.ConstructorResolver.resolveConstructorArguments(ConstructorResolver.java:693) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:198) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:330) ~[spring-beans-5.3.15.jar:5.3.15]
	... 19 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pubsubTemplate' defined in class path resource [http-outbound-gateway.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.gcp.pubsub.core.PubSubTemplate]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.springframework.cloud.gcp.pubsub.core.PubSubTemplate.<init>()
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1334) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1232) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.15.jar:5.3.15]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pubsubTemplate' defined in class path resource [http-outbound-gateway.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.gcp.pubsub.core.PubSubTemplate]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.springframework.cloud.gcp.pubsub.core.PubSubTemplate.<init>()

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:330) ~[spring-beans-5.3.15.jar:5.3.15]
	... 31 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.gcp.pubsub.core.PubSubTemplate]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.springframework.cloud.gcp.pubsub.core.PubSubTemplate.<init>()
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:83) ~[spring-beans-5.3.15.jar:5.3.15]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.gcp.pubsub.core.PubSubTemplate]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.springframework.cloud.gcp.pubsub.core.PubSubTemplate.<init>()

**Comment by waytoharish** [comment]
I tried to change that too

   <bean id="pubsubTemplate" class="org.springframework.cloud.gcp.pubsub.core.PubSubTemplate">
        <constructor-arg index="0" ref="publisherFactory"/>
        <constructor-arg index="1" value="subscriberFactory"/>
    </bean>

    <bean id="publisherFactory" class="org.springframework.cloud.gcp.pubsub.support.PublisherFactory"/>
    <bean id="subscriberFactory" class="org.springframework.cloud.gcp.pubsub.support.SubscriberFactory"/>

**Comment by elefeint** [comment]
The error message is descriptive: `Failed to instantiate [org.springframework.cloud.gcp.pubsub.core.PubSubTemplate]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.springframework.cloud.gcp.pubsub.core.PubSubTemplate()`. It is true that `PubSubTemplate` does not have a no-arg constructor.

Since you are not using autoconfiguration, you'll also have to set up XML wiring to create `PubSubTemplate`, replicating all of the [autoconfiguration](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/ed87b89b72826fb1dad5bb87f7c12edbb3ccc1bf/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/pubsub/GcpPubSubAutoConfiguration.java#L205) that results in `PubSubTemplate` -- that means creating `PubSubPublisherTemplate`, `PubSubSubscriberTemplate` and passing them to the `PubSubTemplate` constructor.

**Comment by elefeint** [comment]
`DefaultPublisherFactory` and `DefaultSubscriberFactory` also have constructor input requirements.

**Comment by waytoharish** [comment]
Thanks @elefeint .
I am able to do the same using the below XML for future reference
`<int:channel id="myInputChannel"></int:channel>

    <int:service-activator
            input-channel="myInputChannel"
            ref="pubSubHandlere">
    </int:service-activator>

    <bean id="pubSubHandlere" class="org.springframework.cloud.gcp.pubsub.integration.outbound.PubSubMessageHandler">
    <constructor-arg index="0" ref="pubsubTemplate"/>
    <constructor-arg index="1" value="myTopic"/>
    </bean>

    <bean id="pubsubTemplate" class="org.springframework.cloud.gcp.pubsub.core.PubSubTemplate">
        <constructor-arg ref="pubSubPublisherTemplate"/>
        <constructor-arg  ref="pubSubSubscriberTemplate"/>
    </bean>

    <bean id="pubSubPublisherTemplate" class="org.springframework.cloud.gcp.pubsub.core.publisher.PubSubPublisherTemplate">
    <constructor-arg ref="defaultPublisherFactory"/>
  </bean>

    <bean id="pubSubSubscriberTemplate" class="org.springframework.cloud.gcp.pubsub.core.subscriber.PubSubSubscriberTemplate">
        <constructor-arg ref="defaultSubscriberFactory"/>
    </bean>

    <bean id="defaultPublisherFactory" class="org.springframework.cloud.gcp.pubsub.support.DefaultPublisherFactory">
        <constructor-arg ref="defaultGcpProjectIdProvider"/>
    </bean>

    <bean id="defaultSubscriberFactory" class="org.springframework.cloud.gcp.pubsub.support.DefaultSubscriberFactory">
        <constructor-arg ref="defaultGcpProjectIdProvider"/>
    </bean>

    <bean id="defaultGcpProjectIdProvider" class="org.springframework.cloud.gcp.core.DefaultGcpProjectIdProvider"/>`
