### ISSUE TITLE
error handling for spring-cloud-gcp-pubsub-stream-binder integration in webflux

### ISSUE THREAD

**Issue by pg30** [GoogleCloudPlatform/spring-cloud-gcp#1240]
I am trying to integrate gcp pubsub in my webflux project using spring cloud stream.
this my application.yml
```
spring:
  cloud:
    stream:
      function:
        definition: processUserContactsFile
      bindings:
        processUserContactsFile-in-0:
          destination: test_topic
          group: test_group
          binder: pubsub-binder
          contentType: application/json

      binders:
        pubsub-binder:
            type: pubsub
```
and my sink
```
@Slf4j
@Component
@RequiredArgsConstructor
public class UserContactsFilePubSubListener {
    @Bean
    Function<Flux<Message<String>>, Mono<Void>> processUserContactsFile() {
        return file -> file.doOnNext(x -> {
                    BasicAcknowledgeablePubsubMessage basicAcknowledgeablePubsubMessage = x.getHeaders()
                            .get(GcpPubSubHeaders.ORIGINAL_MESSAGE, BasicAcknowledgeablePubsubMessage.class);
                    Map<String, String> attributesMap = basicAcknowledgeablePubsubMessage.getPubsubMessage().getAttributesMap();
                    String bucketId = attributesMap.get("bucketId");
                    String eventType = attributesMap.get("eventType");
                    String objectId = attributesMap.get("objectId");
                    log.info("message {} {}", attributesMap, objectId);
                    if(objectId.contains("710")){
                        throw new DataNotFoundException("throwing exception to test internal error handling behaviour of pubsub");
                    }
                })
                .then();
    }
}
```
the above code works fine when messages are getting processed without any exceptions but when I publish a message which contains "710" in objectId (as defined in the exception) and listener throws exception all subsequent messages are also nacked automatically throwing the following error while other messages should have been normally processed: 
```
2022-08-26 17:32:32.434  WARN 44685 --- [sub-subscriber2] .g.c.s.p.i.i.PubSubInboundChannelAdapter : Sending Spring message [5489367759475492] failed; message neither acked nor nacked.

org.springframework.messaging.MessageDeliveryException: Dispatcher has no subscribers for channel 'growth-service.processUserContactsFile-in-0'.; nested exception is org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers, failedMessage=GenericMessage [payload=byte[1159], {pubsub object info that I cannot publish here}
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:76) ~[spring-integration-core-5.5.6.jar:5.5.6]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:317) ~[spring-integration-core-5.5.6.jar:5.5.6]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:272) ~[spring-integration-core-5.5.6.jar:5.5.6]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187) ~[spring-messaging-5.3.13.jar:5.3.13]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166) ~[spring-messaging-5.3.13.jar:5.3.13]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47) ~[spring-messaging-5.3.13.jar:5.3.13]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109) ~[spring-messaging-5.3.13.jar:5.3.13]
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:208) ~[spring-integration-core-5.5.6.jar:5.5.6]
	at com.google.cloud.spring.pubsub.integration.inbound.PubSubInboundChannelAdapter.consumeMessage(PubSubInboundChannelAdapter.java:144) ~[spring-cloud-gcp-pubsub-3.3.0.jar:3.3.0]
	at com.google.cloud.spring.pubsub.core.subscriber.PubSubSubscriberTemplate.lambda$subscribeAndConvert$1(PubSubSubscriberTemplate.java:173) ~[spring-cloud-gcp-pubsub-3.3.0.jar:3.3.0]
	at com.google.cloud.pubsub.v1.MessageDispatcher$3.run(MessageDispatcher.java:454) ~[google-cloud-pubsub-1.117.0.jar:1.117.0]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
Caused by: org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:139) ~[spring-integration-core-5.5.6.jar:5.5.6]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106) ~[spring-integration-core-5.5.6.jar:5.5.6]
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72) ~[spring-integration-core-5.5.6.jar:5.5.6]
	... 16 common frames omitted
```

And the only solution after this is to purge the messages in the topic and restart the application.
Any help is appreciated, thanks!

**Comment by varapriya** [comment]
call basicAcknowledgeablePubsubMessage.nack() if there is an exception , don't throw it .

if(objectId.contains("710")){
                        basicAcknowledgeablePubsubMessage.nack();
                    }

**Comment by pg30** [comment]
thanks for replying @varapriya 
but acc to documentation ACK and AUTO_ACK modes should automatically nack the messages in case of any error thrown.
then why do we need to manually nack it.

**Comment by elefeint** [comment]
ACK results in automatic nacking, while AUTO_ACK does not ([refdoc](https://googlecloudplatform.github.io/spring-cloud-gcp/3.3.0/reference/html/index.html#acknowledging-messages-and-handling-failures)).

But the problem here has more to do with the reactive pipeline. @varapriya is correct that nacking instead of throwing would avoid this problem. The reason is that when an exception is thrown inside the reactive stream `file -> file.doOnNext(x -> { ... }) .then();`, the stream is completed with error, so no further messages will be processed. This causes subsequent messages to never be processed, reach their acknowledgement deadline and get redelivered. But because the reactive stream has been killed already, there is nobody listening for those messages.

As a matter of reactive style, you may want to use `map()` instead of a side effect in `doOnNext()`. Then the `then()` will likely become unnecessary.

**Comment by pg30** [comment]
@elefeint I understood your point about the stream being closed. 
are there any samples about implementing it in the correct way because even if I use ```map/flatMap``` and return ```Mono.error()``` the stream will get closed after that unless error handling is done upstream (gcp lib in case) and without ```.then()``` I am not able to convert the stream to ```Mono<Void>```

**Comment by elefeint** [comment]
Right, returning error is also a terminal operation. You can either avoid any errors in the reactive code, or try switching to [imperative style](https://spring.io/blog/2019/10/17/spring-cloud-stream-functional-and-reactive#imperative-or-reactive) of Spring Cloud Stream. The [Sink example in this project](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-stream-functional-sample/spring-cloud-gcp-pubsub-stream-functional-sample-sink) uses imperative style.
