### ISSUE TITLE
Datastore: not equals filter support

### ISSUE THREAD

**Issue by dosomder** [GoogleCloudPlatform/spring-cloud-gcp#1270]
It seems like datastore itself does support not equals filter: https://cloud.google.com/datastore/docs/concepts/queries

If I try to use a not equal filter in my Repository
```
  List<MyObject> findAllByMyIntegerPropertyNot(int myIntegerProperty);
```

I get the following exception
```
Caused by: org.springframework.cloud.gcp.data.datastore.core.mapping.DatastoreDataException: Unsupported predicate keyword: NEGATING_SIMPLE_PROPERTY (1): [IsNot, Not]
	at org.springframework.cloud.gcp.data.datastore.repository.query.PartTreeDatastoreQuery.lambda$applySelectWithFilter$1(PartTreeDatastoreQuery.java:355)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at org.springframework.cloud.gcp.data.datastore.repository.query.PartTreeDatastoreQuery.applySelectWithFilter(PartTreeDatastoreQuery.java:365)
	at org.springframework.cloud.gcp.data.datastore.repository.query.PartTreeDatastoreQuery.applyQueryBody(PartTreeDatastoreQuery.java:296)
	at org.springframework.cloud.gcp.data.datastore.repository.query.PartTreeDatastoreQuery.runQuery(PartTreeDatastoreQuery.java:193)
```

Is it possible to add NOT_EQUALS support?

**Comment by JoeWang1127** [comment]
@dosomder Hi, from the [docs](https://cloud.google.com/datastore/docs/concepts/queries#datastore-datastore-basic-query-java) you mentions, I can see there is a `NOT_EQUAL` filter, anything wrong with that?

**Comment by JoeWang1127** [comment]
@dosomder Hi, we don't support `NOT_EQUAL` for now, please see [here](https://googlecloudplatform.github.io/spring-cloud-gcp/reference/html/index.html#query-methods-by-convention-2) for for information.

As an alternative, you can combine `greater_than` and `less_than` to do the job.
