### ISSUE TITLE
Unable to save POJO using FirestoreReactiveRepository

### ISSUE THREAD

**Issue by Alos** [GoogleCloudPlatform/spring-cloud-gcp#151]
Using Spring Cloud GCP 1.2.6.RELEASE:

```Java
@Repository
public interface RecommendationRepository extends FirestoreReactiveRepository<Recommendation> {}
```

```Java
@Data
public class Recommendation {
  @DocumentId private String id;
  private String contestId;
  private String authorName;
  private String title;
  private String publisher;
  private String comment;
  private String url;
  private String submissionTypeId;
  private Recommender recommender;
}
```

```Java
@Data
public class Recommender {
  private String name;
  private String email;
}
```

When saving a recommendation I get the following error:

```
o.grpc.StatusRuntimeException: INVALID_ARGUMENT: Document name "projects/<PROJECT_NAME>/databases/(default)/documents/recommendation/" has invalid trailing "/".
	at io.grpc.Status.asRuntimeException(Status.java:533) ~[grpc-api-1.33.0.jar:1.33.0]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Handler com.submie.mocksha.controllers.RecommendationController#save(Recommendation, String, ServerHttpRequest) [DispatcherHandler]
	|_ checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
	|_ checkpoint ⇢ HTTP POST "/api/v1/recommendations" [ExceptionHandlingWebHandler]
Stack trace:
		at io.grpc.Status.asRuntimeException(Status.java:533) ~[grpc-api-1.33.0.jar:1.33.0]
		at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478) ~[grpc-stub-1.33.0.jar:1.33.0]
		at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:616) ~[grpc-core-1.33.0.jar:1.33.0]
		at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:69) ~[grpc-core-1.33.0.jar:1.33.0]
		at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:802) ~[grpc-core-1.33.0.jar:1.33.0]
		at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:781) ~[grpc-core-1.33.0.jar:1.33.0]
		at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.33.0.jar:1.33.0]
		at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[grpc-core-1.33.0.jar:1.33.0]
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
		at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]
```

**Comment by Alos** [comment]
It looks like Spring Cloud GCP will not set the `@DocumentId` if the value for the id is an empty String, it only works if the value is null.

**Comment by meltsufin** [comment]
That right, only `null` will trigger id generation, and we document it as such in our refdoc. I believe it's actually the Firestore client library that has that logic. So, unless you feel we should change this behavior, we can close this issue as "works as intended".

**Comment by Alos** [comment]
LGTM
