### ISSUE TITLE
spring-cloud-gcp-starter-trace 4.0.0 fails with Encoder doesn't match Sender: JSON PROTO3

### ISSUE THREAD

**Issue by codependent** [GoogleCloudPlatform/spring-cloud-gcp#1554]
**Describe the bug**
I've just upgraded a Spring Boot application to 3.0.2, Cloud 2022.0.1 and Spring Cloud GCP 4.0.0. 

Cloud Trace integration is failing with the following exception:

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'spanReporter' defined in class path resource [org/springframework/boot/actuate/autoconfigure/tracing/zipkin/ZipkinConfigurations$ReporterConfiguration.class]: Failed to instantiate [zipkin2.reporter.AsyncReporter]: Factory method 'spanReporter' threw exception with message: Encoder doesn't match Sender: JSON PROTO3
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:657)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:645)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1324)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1161)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:561)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1405)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1325)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:885)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:789)
	... 191 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [zipkin2.reporter.AsyncReporter]: Factory method 'spanReporter' threw exception with message: Encoder doesn't match Sender: JSON PROTO3
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 205 common frames omitted
Caused by: java.lang.IllegalArgumentException: Encoder doesn't match Sender: JSON PROTO3
	at zipkin2.reporter.AsyncReporter$Builder.build(AsyncReporter.java:201)
	at org.springframework.boot.actuate.autoconfigure.tracing.zipkin.ZipkinConfigurations$ReporterConfiguration.spanReporter(ZipkinConfigurations.java:123)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139)
	... 206 common frames omitted
```

The application is a Spring Cloud Gateway with the following dependencies:

```
plugins {
    id("org.springframework.boot") version "3.0.2"
    id("io.spring.dependency-management") version "1.1.0"  
    jacoco
    kotlin("jvm") version "1.8.0"
    kotlin("plugin.spring") version "1.8.0"
}

java.sourceCompatibility = VERSION_17

repositories {
    maven { url = uri("https://repo.spring.io/milestone") }
    maven { url = uri("https://repo.spring.io/snapshot") }
    mavenCentral()
    maven { url = uri("https://packages.confluent.io/maven") }
}

extra["springCloudVersion"] = "2022.0.1"
extra["springCloudGcpVersion"] = "4.0.0"

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-security")
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.jetbrains.kotlin:kotlin-reflect")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("org.springframework.cloud:spring-cloud-starter-bootstrap")
    implementation("org.springframework.cloud:spring-cloud-starter-gateway")
    implementation("org.springframework.cloud:spring-cloud-loadbalancer")
    implementation("org.springframework.boot:spring-boot-starter-data-redis-reactive")
    implementation("org.springframework.cloud:spring-cloud-starter-kubernetes-fabric8-config")
    implementation("org.springframework.boot:spring-boot-starter-oauth2-client")
    implementation("commons-net:commons-net:3.9.0")
    implementation("io.micrometer:micrometer-tracing-bridge-brave")
    implementation("com.google.cloud:spring-cloud-gcp-starter-trace")
    implementation("com.google.cloud:spring-cloud-gcp-starter-logging")
    implementation("io.micrometer:micrometer-registry-prometheus")
    implementation("io.github.mweirauch:micrometer-jvm-extras:0.2.2")
    implementation("io.projectreactor.kotlin:reactor-kotlin-extensions")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
    implementation("io.grpc:grpc-netty:1.52.1")
    
dependencyManagement {
    imports {
        mavenBom("org.springframework.cloud:spring-cloud-dependencies:${property("springCloudVersion")}")
        mavenBom("com.google.cloud:spring-cloud-gcp-dependencies:${property("springCloudGcpVersion")}")
    }
}    
```

**Comment by JoeWang1127** [comment]
Hi @codependent, at an initial investigation, you should exclude `ZipkinAutoConfiguration` in your application. Please see [the sample](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples/spring-cloud-gcp-trace-sample) for more info.

Also, it's better if you can post a minimum project to reproduce the issue.

**Comment by codependent** [comment]
@JoeWang1127 Thanks for the hint, once `ZipkinAutoConfiguration` was excluded it worked fine. It may be useful to include that info in the documentation.

**Comment by JoeWang1127** [comment]
@codependent Hi, I've fixed the issue so that you don't need to exclude `ZipkinAutoConfiguration` anymore.

Please upgrade to the newest version when it's available.

**Comment by codependent** [comment]
Thanks for the quick fix 🚀

**Comment by JoeWang1127** [comment]
@virgilsb Hi, thanks for sharing this problem.

Could you please create a new issue and link a minimum project that can reproduce the issue?

**Comment by virgilsb** [comment]
@JoeWang1127 I logged #1630
