### ISSUE TITLE
Spring Cloud Datastore - Method annotated with @Transactional calling other methods that are not annotated with @Transactional still includes them in transaction

### ISSUE THREAD

**Issue by tlaloc2049** [GoogleCloudPlatform/spring-cloud-gcp#1661]
**Describe the bug**

+com.google.cloud:spring-cloud-gcp-starter-data-datastore
+springCloudGcpVersion=3.4.5
+springBootVersion=2.6.14

The documentation suggests methods annotated with @Transactional called from another annotated method will also be included in the transaction. I was expecting methods not annotated called from an annotated method would not be included in the transaction.

https://cloud.spring.io/spring-cloud-static/Greenwich.RC2/multi/multi__spring_data_cloud_datastore.html#_declarative_transactions_with_transactional_annotation_2

**Sample**

—- Entity classes —-

```
@Entity(name = "User")
public class User {
    @Id 
    String id;
}

@Entity(name = "UserMetadata")
public class UserMetadata {
    @Id 
    String id;
    
    String eventId;
}
```

—- Method definitions —-

```
@Transactional
public User getUser(String id) {
   return repository.findById(id).orElse(null);
}

public UserMetadata getUserMetadata(String id, String eventId) {
    return repository.findByIdAndEventId(id, eventId);
}

@Transactional
public User saveUser(User user) {
    return repository.save(user);
}
```

—-

The next method call includes all datastore calls into one single transaction and throws an exception because the query in getUserMetadata should not be included in a transaction if it doesn't have an ancestor.

```
@Transactional
public void saveTransaction(String id, String eventId) {
    User user = getUser(id);
    UserMetadata metadata = getUserMetadata(id, eventId);
    user = saveUser(user);
}
```

**Comment by emmileaf** [comment]
> The next method call includes all datastore calls into one single transaction and throws an exception because the query in getUserMetadata should not be included in a transaction if it doesn't have an ancestor.

@tlaloc2049 To check that I am understanding this issue description correctly: did you expect the call to `getUserMetadata(id, eventId)` to be skipped because it was not annotated, but instead observe an exception thrown as part of the call being unexpectedly executed as part of the transaction? Could you help share a stacktrace or additional logs from the exception?

> If a method annotated with Transactional calls another method also annotated, then both methods will work within the same transaction.

This line you are referring to in the [documentation](https://googlecloudplatform.github.io/spring-cloud-gcp/reference/html/index.html#declarative-transactions-with-transactional-annotation-2) is more of an explanation on the annotation nesting (the top-level annotated method will encapsulate one transaction), and not one on statement filtering. Is there more context behind your use case of wanting the `getUserMetadata`call as part of the `saveTransaction` body, but not included as part of that transaction?

**Comment by tlaloc2049** [comment]
Hi @emmileaf,

> To check that I am understanding this issue description correctly: did you expect the call to getUserMetadata(id, eventId) to be skipped because it was not annotated, but instead observe an exception thrown as part of the call being unexpectedly executed as part of the transaction? Could you help share a stacktrace or additional logs from the exception?

That's correct. 

Here's the stacktrace:

> com.google.datastore.v1.client.DatastoreException: queries inside transactions must have ancestors
	at com.google.datastore.v1.client.RemoteRpc.makeException(RemoteRpc.java:171) ~[datastore-v1-proto-client-2.13.6.jar:2.13.6]
	at com.google.datastore.v1.client.RemoteRpc.makeException(RemoteRpc.java:239) ~[datastore-v1-proto-client-2.13.6.jar:2.13.6]
	at com.google.datastore.v1.client.RemoteRpc.call(RemoteRpc.java:100) ~[datastore-v1-proto-client-2.13.6.jar:2.13.6]
	at com.google.datastore.v1.client.Datastore.runQuery(Datastore.java:119) ~[datastore-v1-proto-client-2.13.6.jar:2.13.6]
	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.runQuery(HttpDatastoreRpc.java:200) ~[google-cloud-datastore-2.13.6.jar:2.13.6]
	at com.google.cloud.datastore.DatastoreImpl$1.call(DatastoreImpl.java:220) ~[google-cloud-datastore-2.13.6.jar:2.13.6]
	at com.google.cloud.datastore.DatastoreImpl$1.call(DatastoreImpl.java:217) ~[google-cloud-datastore-2.13.6.jar:2.13.6]
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103) ~[gax-2.23.2.jar:2.23.2]
	at com.google.cloud.RetryHelper.run(RetryHelper.java:76) ~[google-cloud-core-2.12.0.jar:2.12.0]
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50) ~[google-cloud-core-2.12.0.jar:2.12.0]
	at com.google.cloud.datastore.DatastoreImpl.runQuery(DatastoreImpl.java:216) ~[google-cloud-datastore-2.13.6.jar:2.13.6]
	at com.google.cloud.datastore.QueryResultsImpl.sendRequest(QueryResultsImpl.java:76) ~[google-cloud-datastore-2.13.6.jar:2.13.6]
	at com.google.cloud.datastore.QueryResultsImpl.<init>(QueryResultsImpl.java:62) ~[google-cloud-datastore-2.13.6.jar:2.13.6]
	at com.google.cloud.datastore.DatastoreImpl.run(DatastoreImpl.java:197) ~[google-cloud-datastore-2.13.6.jar:2.13.6]
	at com.google.cloud.datastore.TransactionImpl.run(TransactionImpl.java:102) ~[google-cloud-datastore-2.13.6.jar:2.13.6]
	at com.google.cloud.spring.data.datastore.core.DatastoreTemplate.queryKeysOrEntities(DatastoreTemplate.java:322) ~[spring-cloud-gcp-data-datastore-3.4.6.jar:3.4.6]
	at com.google.cloud.spring.data.datastore.repository.query.PartTreeDatastoreQuery.runQuery(PartTreeDatastoreQuery.java:201) ~[spring-cloud-gcp-data-datastore-3.4.6.jar:3.4.6]
	at com.google.cloud.spring.data.datastore.repository.query.PartTreeDatastoreQuery.execute(PartTreeDatastoreQuery.java:174) ~[spring-cloud-gcp-data-datastore-3.4.6.jar:3.4.6]
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:137) ~[spring-data-commons-2.7.8.jar:2.7.8]
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:121) ~[spring-data-commons-2.7.8.jar:2.7.8]
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:160) ~[spring-data-commons-2.7.8.jar:2.7.8]
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:139) ~[spring-data-commons-2.7.8.jar:2.7.8]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.25.jar:5.3.25]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.25.jar:5.3.25]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.25.jar:5.3.25]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215) ~[spring-aop-5.3.25.jar:5.3.25]
	at com.sun.proxy.$Proxy62.findByIdAndEventId(Unknown Source) ~[na:na]
	at com.example.demo.UserMetadataManager.getUserMetadata(UserMetadataManager.java:17) ~[main/:na]
	at com.example.demo.StoreManager.saveTransaction(StoreManager.java:26) ~[main/:na]
	at com.example.demo.StoreManager$$FastClassBySpringCGLIB$$85ab1826.invoke(<generated>) ~[main/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.25.jar:5.3.25]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.25.jar:5.3.25]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.25.jar:5.3.25]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.25.jar:5.3.25]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-5.3.25.jar:5.3.25]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) ~[spring-tx-5.3.25.jar:5.3.25]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-5.3.25.jar:5.3.25]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.25.jar:5.3.25]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.25.jar:5.3.25]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.25.jar:5.3.25]
	at com.example.demo.StoreManager$$EnhancerBySpringCGLIB$$f4ee9ecb.saveTransaction(<generated>) ~[main/:na]
	at com.example.demo.DemoController.getUser(DemoController.java:27) ~[main/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.25.jar:5.3.25]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.25.jar:5.3.25]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.25.jar:5.3.25]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.25.jar:5.3.25]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.25.jar:5.3.25]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.25.jar:5.3.25]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1071) ~[spring-webmvc-5.3.25.jar:5.3.25]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:964) ~[spring-webmvc-5.3.25.jar:5.3.25]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.25.jar:5.3.25]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.3.25.jar:5.3.25]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:670) ~[tomcat-embed-core-9.0.71.jar:4.0.FR]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.25.jar:5.3.25]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:779) ~[tomcat-embed-core-9.0.71.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.71.jar:9.0.71]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.71.jar:9.0.71]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.71.jar:9.0.71]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.71.jar:9.0.71]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.71.jar:9.0.71]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.25.jar:5.3.25]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.25.jar:5.3.25]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.71.jar:9.0.71]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.71.jar:9.0.71]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.25.jar:5.3.25]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.25.jar:5.3.25]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.71.jar:9.0.71]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.71.jar:9.0.71]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.25.jar:5.3.25]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.25.jar:5.3.25]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.71.jar:9.0.71]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.71.jar:9.0.71]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177) ~[tomcat-embed-core-9.0.71.jar:9.0.71]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.71.jar:9.0.71]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[tomcat-embed-core-9.0.71.jar:9.0.71]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[tomcat-embed-core-9.0.71.jar:9.0.71]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.71.jar:9.0.71]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.71.jar:9.0.71]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) ~[tomcat-embed-core-9.0.71.jar:9.0.71]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) ~[tomcat-embed-core-9.0.71.jar:9.0.71]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.71.jar:9.0.71]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891) ~[tomcat-embed-core-9.0.71.jar:9.0.71]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784) ~[tomcat-embed-core-9.0.71.jar:9.0.71]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.71.jar:9.0.71]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.71.jar:9.0.71]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.71.jar:9.0.71]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.71.jar:9.0.71]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]

**Comment by tlaloc2049** [comment]
> This line you are referring to in the [documentation](https://googlecloudplatform.github.io/spring-cloud-gcp/reference/html/index.html#declarative-transactions-with-transactional-annotation-2) is more of an explanation on the annotation nesting (the top-level annotated method will encapsulate one transaction), and not one on statement filtering. Is there more context behind your use case of wanting the getUserMetadata call as part of the saveTransaction body, but not included as part of that transaction?

I'm doing some code refactoring and see many places where an entity is read, modified and then saved with the intention of having it within a transaction. The problem is that between those steps to read and write the entity there are multiple methods called and sometimes deep in the stack trace of those methods some unrelated query runs and throws that exception (only with a runQuery, getting a single entity by key works fine).

With Datastore's low level api I can leave those unrelated queries out of the transaction, but then need to pass around the transaction object between the different methods that use it.

We're in the planning phase of the refactor and experimenting to see if we should use annotation based transactions or the low level api.

**Comment by emmileaf** [comment]
Thanks for clarifying! In this case, you are observing the intended behaviour. 

In the context of your provided snippet, the documentation means to explain that everything included in the outermost annotated `saveTransaction` method now works within the same transaction - even calls to other methods annotated with `@ Transactional` that would otherwise be wrapped in individual transactions. This does not mean any filtering is done to exclude calls to non-annotated methods, which is why you are seeing the underlying query from `getUserMetadata` throw the exception. 

Perhaps specific filtering logic can be added programmatically within method bodies to exclude the problematic query from running? I understand that the actual scenario you are trying to work around is more complicated than this snippet - Spring’s documentation on [Declarative Transaction Management](https://docs.spring.io/spring-framework/docs/current/reference/html/data-access.html#transaction-declarative) could be more of help here.

**Comment by tejaswibm** [comment]
`@Transactional` applied on 2 different beans, perform separate transactions and are not enclosed within single transaction. What I mean here in the above case, 
`@Transactional
public void saveTransaction(String id, String eventId)`
defined in, lets say `Service Layer` and 
`@Transactional
public User getUser(String id)`
defined in `DAO layer`, and when `saveTransaction()` calls `getUser()`, both will be performed in separate transactions.
Is my understanding correct ?
