### ISSUE TITLE
Firestore - findAllByIdNotIn not working

### ISSUE THREAD

**Issue by Tera** [GoogleCloudPlatform/spring-cloud-gcp#1746]
**Describe the bug**
Currently there isn't a way to execute a query searching for all documents with DocumentID NOT IN a collection

I've added this method to a `FirestoreReactiveRepository`

```
@Repository
interface CourtesyCallRepository : FirestoreReactiveRepository<CourtesyCall> {
    suspend fun findAllByIdNotIn(ids: List<String>, pageable: Pageable): Flow<CourtesyCall>
}
```

but executing this code in a test with testcontainers returns this error:

```
class java.util.Arrays$ArrayList cannot be cast to class java.lang.String (java.util.Arrays$ArrayList and java.lang.String are in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class java.util.Arrays$ArrayList cannot be cast to class java.lang.String (java.util.Arrays$ArrayList and java.lang.String are in module java.base of loader 'bootstrap')
	at com.google.cloud.spring.data.firestore.repository.query.PartTreeFirestoreQuery.lambda$createBuilderWithFilter$2(PartTreeFirestoreQuery.java:250)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.google.cloud.spring.data.firestore.repository.query.PartTreeFirestoreQuery.createBuilderWithFilter(PartTreeFirestoreQuery.java:223)
	at com.google.cloud.spring.data.firestore.repository.query.PartTreeFirestoreQuery.execute(PartTreeFirestoreQuery.java:144)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvokeReactiveToSuspended(RepositoryMethodInvoker.java:174)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:119)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:164)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:143)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.data.repository.core.support.MethodInvocationValidator.invoke(MethodInvocationValidator.java:94)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:218)
	at jdk.proxy3/jdk.proxy3.$Proxy151.findAllByIdNotIn(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:218)
	at jdk.proxy3/jdk.proxy3.$Proxy151.findAllByIdNotIn(Unknown Source)

```

Looking into `com.google.cloud.spring.data.firestore.repository.query.PartTreeFirestoreQuery` code the error is caused by:

```
  // In Firestore, a field that is used as a document ID can only be of String type
    fieldFilterBuilder.setValue(
        Value.newBuilder()
            .setReferenceValue(
                this.reactiveOperations.buildResourceName(
                    persistentEntity, (String) value)));
  } else {
    fieldFilterBuilder.setValue(this.classMapper.toFirestoreValue(value));
  }
```
If field in `not in` clause is the one annotated with `@DocumentId` it will automatically cast it to string but in a not In clause the value is an array not a string so in that case it should execute the code in else branch.

**Sample**
To replicate issue you can use this entity class:
```
@Document(collectionName = "courtesyCall")
data class CourtesyCall(
    @DocumentId
    var id: String? = null,
)
```
the above repository and this test:

```
 @Test
    fun shouldFindAllCourtesyCallsExceptsTheOnesWithTheSpecifiedIds() {
        runBlocking {
            val template = CourtesyCall()

            repository.save(template.copy(id = "1")).awaitSingle()
            repository.save(template.copy(id = "2")).awaitSingle()
            repository.save(template.copy(id = "3")).awaitSingle()

            val result = repository.findAllByIdNotIn(listOf("1", "3"), Pageable.unpaged()).toList(mutableListOf())

            assertThat(result.map { it.id }, contains("2"))
        }
    }
```

**Comment by philly-vanilly** [comment]
I have the same issue. It seems findByXxxIn() where Xxx is not @DocumentId (so you have to assign an own identifier like UUID) is a workaround albeit a shitty one as FireStore probably uses the documentId for indexing and this might affect performance or costs (?)

**Comment by meltsufin** [comment]
@philly-vanilly I think this is it: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/3b0ced5c577b6491b3991de685914cabfae808d6/spring-cloud-gcp-data-firestore/src/main/java/com/google/cloud/spring/data/firestore/FirestoreTemplate.java#L162-L168

Feel free to look around the codebase yourself though.

**Comment by philly-vanilly** [comment]
@meltsufin I am not quite sure how the "In" filter combines with the "findAll" (haven't found the "In" part in the FiestoreTemplate), but having tested a native "whereIn" via

```
  @Autowired
  var firestore: Firestore? = null
  
  val result = firestore!!.collection("persons")
      .whereIn("id", listOf(personOne.id, personTwo.id)).get().get()
```

I am getting nothing either, only for other, non-id fields the whereIn query works. If there is no other way but to use a batch operation, I think it might be better to disallow findAllById(Not)In or throw an error, so it does not cause n number of requests internally. Might also be an issue with custom indices, idk...

**Comment by meltsufin** [comment]
No response from OP. Closing.
