### ISSUE TITLE
Spring GCP Pubsub Out of Memory issues when processing bulk messages of 400k and each message of size >100KB

### ISSUE THREAD

**Issue by patan12** [GoogleCloudPlatform/spring-cloud-gcp#1801]
I am using stream bridge to send messages over pubsub

I have some 100k messages that I need to push to pubsub. I am using executor pool of 5 threads to do the job
```

@Async 
public void process(){
List<MyObject> list = getListFromDb();
fetchAndPublish(list);
}

private void fetchAndPublish(List<MyObject> list) {
    int threads = 5 < list.size() ? 5 : list.size();
    ExecutorService es = Executors.newFixedThreadPool(threads);
    CompletableFuture<?>[] futures = list.stream()
        .map(s -> new MyRunnable(s))
        .map(task -> CompletableFuture.runAsync(task, es))
        .toArray(CompletableFuture[]::new);
    CompletableFuture.allOf(futures).join();
    es.shutdown();
  }
  
   public class MyRunnable implements Runnable {

    private final MyObject myObject;

    public MyRunnable(MyObject myObject) {
      this.myObject = myObject;
    }

    @Override
    public void run() {
        try {
          Message<MyObject> message = MessageBuilder.withPayload(myObject)
              .build();
          messagePublisherService.publish(message);
        } catch (Exception exception) {
          log.error("Failed ", exception);
        }
    }
  }
```
  I am using stream bridge to send messages over pubsub

I have some 100k messages that I need to push to pubsub. I am using executor pool of 5 threads to do the job

private void fetchAndPublish(List<MyObject> list) {
    int threads = 5 < list.size() ? 5 : list.size();
    ExecutorService es = Executors.newFixedThreadPool(threads);
    CompletableFuture<?>[] futures = list.stream()
        .map(s -> new MyRunnable(s))
        .map(task -> CompletableFuture.runAsync(task, es))
        .toArray(CompletableFuture[]::new);
    CompletableFuture.allOf(futures).join();
    es.shutdown();
  }
  
   public class MyRunnable implements Runnable {

    private final MyObject myObject;

    public MyRunnable(MyObject myObject) {
      this.myObject = myObject;
    }

    @Override
    public void run() {
        try {
          Message<MyObject> message = MessageBuilder.withPayload(myObject)
              .build();
          messagePublisherService.publish(message);
        } catch (Exception exception) {
          log.error("Failed ", exception);
        }
    }
  }
  
My service to publish message is here

```
@Component
@Slf4j
public class MessagePublisherService {

  @Value("${publish.destination:myDes-out-0}")
  private String destination;

  @Autowired
  private StreamBridge streamBridge;

  public void publish(Message<MyObject> message) {
    log.info("publishing {}", message.getPayload().getId());
    streamBridge.send(destination, message);
  }
}
```

It works good, but after some time I am getting Out of memory exception. What I am noticing is the memory is not release as soon as the data is pushed to streamBridge

I have 16GB of heap memory, and it gets filled very quickly. My data is not that huge.

Dynatrace Stats I can see the initially the publish call to pubsubs took 200+ms. But progressively this time was increased and occuapaid resources

This is my Dynatrace slowly we can see that in the beginning the requests to PUBLISH to pubsub took small time

![startimage png](https://user-images.githubusercontent.com/24582170/236380922-2b2b344d-3fbc-4597-99f9-5ff327dc4d64.jpg)

After some time it started to take so much time and occupy resources

![laterImage png](https://user-images.githubusercontent.com/24582170/236380963-d97856e0-b667-485f-9467-8871be4ef382.jpg)

I am using cloud run with 16GB memory and 8 cpu cores
spring boot 2.7.11
spring cloud 2021.0.7
gcp cloud 3.4.9

**Comment by patan12** [comment]
Thank you. I wil try to get some reproducible code. At the moment I donot have sample code and memory report. I will check and get back.

**Comment by patan12** [comment]
@JoeWang1127 I do not have sample code. I will check if I can get. What I have seen is that grpc pubsub publish taking more time gradually

**Comment by patan12** [comment]
@JoeWang1127 

https://github.com/patan12/pubsub

java -jar pubsub-0.0.1-SNAPSHOT.jar -Xmx2g

I have mocked same file for the sake of simplicity. where ever possible I have mocked data to depict the actual issue
```

java.lang.OutOfMemoryError: Direct buffer memory
        at java.base/java.nio.Bits.reserveMemory(Bits.java:175) ~[na:na]
        at java.base/java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:118) ~[na:na]
        at java.base/java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:317) ~[na:na]
        at io.grpc.netty.shaded.io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:701) ~[grpc-netty-shaded-1.54.0.jar!/:1.54.0]
        at io.grpc.netty.shaded.io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:676) ~[grpc-netty-shaded-1.54.0.jar!/:1.54.0]
        at io.grpc.netty.shaded.io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:215) ~[grpc-netty-shaded-1.54.0.jar!/:1.54.0]
        at io.grpc.netty.shaded.io.netty.buffer.PoolArena.tcacheAllocateNormal(PoolArena.java:197) ~[grpc-netty-shaded-1.54.0.jar!/:1.54.0]
        at io.grpc.netty.shaded.io.netty.buffer.PoolArena.allocate(PoolArena.java:139) ~[grpc-netty-shaded-1.54.0.jar!/:1.54.0]
        at io.grpc.netty.shaded.io.netty.buffer.PoolArena.allocate(PoolArena.java:129) ~[grpc-netty-shaded-1.54.0.jar!/:1.54.0]
        at io.grpc.netty.shaded.io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:396) ~[grpc-netty-shaded-1.54.0.jar!/:1.54.0]
        at io.grpc.netty.shaded.io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188) ~[grpc-netty-shaded-1.54.0.jar!/:1.54.0]
        at io.grpc.netty.shaded.io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:124) ~[grpc-netty-shaded-1.54.0.jar!/:1.54.0]
        at io.grpc.netty.shaded.io.grpc.netty.NettyWritableBufferAllocator.allocate(NettyWritableBufferAllocator.java:51) ~[grpc-netty-shaded-1.54.0.jar!/:1.54.0]
        at io.grpc.internal.MessageFramer.writeKnownLengthUncompressed(MessageFramer.java:230) ~[grpc-core-1.54.0.jar!/:1.54.0]
        at io.grpc.internal.MessageFramer.writeUncompressed(MessageFramer.java:169) ~[grpc-core-1.54.0.jar!/:1.54.0]
        at io.grpc.internal.MessageFramer.writePayload(MessageFramer.java:142) ~[grpc-core-1.54.0.jar!/:1.54.0]
        at io.grpc.internal.AbstractStream.writeMessage(AbstractStream.java:65) ~[grpc-core-1.54.0.jar!/:1.54.0]
        at io.grpc.internal.ForwardingClientStream.writeMessage(ForwardingClientStream.java:37) ~[grpc-core-1.54.0.jar!/:1.54.0]
        at io.grpc.internal.RetriableStream$1SendMessageEntry.runWith(RetriableStream.java:562) ~[grpc-core-1.54.0.jar!/:1.54.0]
        at io.grpc.internal.RetriableStream.delayOrExecute(RetriableStream.java:539) ~[grpc-core-1.54.0.jar!/:1.54.0]
        at io.grpc.internal.RetriableStream.sendMessage(RetriableStream.java:570) ~[grpc-core-1.54.0.jar!/:1.54.0]
        at io.grpc.internal.ClientCallImpl.sendMessageInternal(ClientCallImpl.java:534) ~[grpc-core-1.54.0.jar!/:1.54.0]
        at io.grpc.internal.ClientCallImpl.sendMessage(ClientCallImpl.java:520) ~[grpc-core-1.54.0.jar!/:1.54.0]
        at io.grpc.ForwardingClientCall.sendMessage(ForwardingClientCall.java:37) ~[grpc-api-1.54.0.jar!/:1.54.0]
        at io.grpc.ForwardingClientCall.sendMessage(ForwardingClientCall.java:37) ~[grpc-api-1.54.0.jar!/:1.54.0]
        at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:317) ~[grpc-stub-1.54.0.jar!/:1.54.0]
        at io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:227) ~[grpc-stub-1.54.0.jar!/:1.54.0]
        at com.google.api.gax.grpc.GrpcDirectCallable.futureCall(GrpcDirectCallable.java:63) ~[gax-grpc-2.25.0.jar!/:2.25.0]
        at com.google.api.gax.grpc.GrpcUnaryRequestParamCallable.futureCall(GrpcUnaryRequestParamCallable.java:65) ~[gax-grpc-2.25.0.jar!/:2.25.0]
        at com.google.api.gax.grpc.GrpcExceptionCallable.futureCall(GrpcExceptionCallable.java:64) ~[gax-grpc-2.25.0.jar!/:2.25.0]
        at com.google.api.gax.rpc.AttemptCallable.call(AttemptCallable.java:87) ~[gax-2.25.0.jar!/:2.25.0]
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131) ~[guava-31.1-jre.jar!/:na]
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74) ~[guava-31.1-jre.jar!/:na]
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82) ~[guava-31.1-jre.jar!/:na]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
```

**Comment by meltsufin** [comment]
You are dealing with 400K x 100KB ~= 40GB of messages without any throttling. So, it's not surprising that you would run out of memory on a 16GB machine. I think that pulling instead of streaming would give you more control. Would you be able to use `PubSubTemplate` directly?

**Comment by patan12** [comment]
@meltsufin Actually I am not loading all at once. I am processing one by one by fetching from db. So It's batch of 100kb messages at a time but not all at once

**Comment by meltsufin** [comment]
I guess we need to better understand what happens as part of `streamBridge.send(destination, message)`. Does it only return after the message finished publishing to Pub/Sub?

**Comment by patan12** [comment]
@meltsufin I tried with pubsub template as well. I have faced similar issue. If needed I can submit the sample project as well.

**Comment by meltsufin** [comment]
A sample would be great! Many thanks!

**Comment by patan12** [comment]
> A sample would be great! Many thanks!

https://github.com/patan12/pubsub

**Comment by meltsufin** [comment]
@patan12 Do you have instructions on how to reproduce the error?
Also, have you tried configuring `spring.cloud.stream.gcp.pubsub.default.producer.sync=true` because by default sending is asynchronous.

**Comment by patan12** [comment]
> @patan12 Do you have instructions on how to reproduce the error? Also, have you tried configuring `spring.cloud.stream.gcp.pubsub.default.producer.sync=true` because by default sending is asynchronous.

I have given the sample and steps above

1. clone the project . 
2. gradle clean build
3. launch the jar 
        java -jar pubsub-0.0.1-SNAPSHOT.jar -Xmx2g

As the program progress. we can see that the time taken to put in pub sub increases. And then it crashes with OOM

you can try changing the heap memory as well and try with 4gb too

I tried with the sync option but its taking too long to complete push, as a result program did not progress that far.

**Comment by JoeWang1127** [comment]
Thanks, I'll take a look.

**Comment by meltsufin** [comment]
@patan12 Would you mind trying to publish using `PubSubTemplate` directly? When your app logs `Publishing Activity completed`, how do you know that it's actually true as you're using asynchronous stream binder sending?

**Comment by JoeWang1127** [comment]
Close as no responds from customer, please reopen it if still needed.
