### ISSUE TITLE
findAll(Pageable pageable) throwing error No value at JSON path “$.data.length()

### ISSUE THREAD

**Issue by ivanvandessel-wk** [GoogleCloudPlatform/spring-cloud-gcp#2109]
**Describe the bug**
upgrading from 4.3.0 to 4.3.1 or higher causes an error to be thrown by our call to findAll(Pageable pageable)

 java.lang.AssertionError: No value at JSON path “$.data.length()”
 at org.springframework.test.util.JsonPathExpectationsHelper.evaluateJsonPath(JsonPathExpectationsHelper.java:302)
 at org.springframework.test.util.JsonPathExpectationsHelper.assertValue(JsonPathExpectationsHelper.java:73)
 at org.springframework.test.web.servlet.result.JsonPathResultMatchers.lambda$value$0(JsonPathResultMatchers.java:87)

This is happening in our api get calls from our running service and also from our mocked service unit tests for the same call.

In simple form we are doing this and getting the failure: 

final JpaUserRepository userRepository;
Pageable pageRequest = new OffsetBasedPageRequest(offset, limit);
userRepository.findAll(pageRequest);

**Comment by meltsufin** [comment]
Can you provide a reproducer? We are on version `4.7.1` currently. So, please try latest. Also, the stacktrace is not showing any Spring Cloud GCP code, just Spring Framework.

**Comment by meltsufin** [comment]
Not reproducible.
