### ISSUE TITLE
Spring Boot+datastore throws "Type must not be Null" when JsonNode is used as attribute on a Datastore Entity

### ISSUE THREAD

**Issue by jevanio** [GoogleCloudPlatform/spring-cloud-gcp#2774]
**Describe the bug**
Hey folks,
I been working on a spring boot project which use Datastore as backend. On this project, I'm trying to update jackson dependencies from the current version it has (2.13.4) to a newer one (2.16.2) but I'm getting an issue on a Datastore Entity which use JsonNode as attribute.

This is the error:
![image](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/assets/1214408/51fc959e-d933-4f06-bd3a-8f537492a483)

I have seen that, after upgrading to jackson 2.14.X or higher, I'm getting an error on bean creation which only says "Type must not be null". After a lot of debugging, and creating a SpringBoot+Datastore project from scratch, I found that if I remove a JsonNode attribute from a Datastore Entity the service starts and beans can be creater. I must mention that this JsonNode attribute has been included from long time ago and it was working with Jackson 2.13.4.

The entity itself it just have 2 attributes with getter/setter
![image](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/assets/1214408/017b68d8-a67b-4db9-ae78-5f17552131da)

I feel that there's some configuration or dependencies which could be required but, as of now, I haven't been able to identify which change is missing. I have check Jackson Releases to see if there's any breaking change or mention but so far no luck.

Can you guide me if there's a configuration required to work with JsonNodes on GCP Cloud DataStore Entities?
Thanks in advance for any insights you can give me

**Sample**
This is sample project with Java 17, the issue can be reproduce changing jackson version to 2.14.X or higher. It's a base spring boot project with only 4 classes and no custom logic.
https://github.com/jevanio/demoProject

Note: To start the project on local, it's required to include as Environment Variable **JDK_JAVA_OPTIONS=--add-opens java.base/java.math=ALL-UNNAMED** to fix a math library error
![image](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/assets/1214408/de17f4a6-3cb6-41f3-8212-56739bcfb3d3)

**Comment by suztomo** [comment]
@jevanio Thank you for reporting the issue. Would you add more stacktrace?

![image](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/assets/28604/31c6d553-9359-4213-8e27-6d7b3fd6440c)

Memo: Recent GCP client libraries have been built with Jackson 2.17.0 https://github.com/googleapis/sdk-platform-java/blob/ba648ceac869d4fab1a9cbeb40f2e04f69dad4e3/java-shared-dependencies/third-party-dependencies/pom.xml#L32C22-L32C28

@jevanio Do you observe the same problem with Jackson 2.17.0 and spring-cloud-gcp v5.1.2?

**Comment by jevanio** [comment]
Hey @suztomo, thanks for your answer
So, I tried upgrading to Jackson 2.17.0 and Spring-cloud-gcp 5.1.2 but the issue persist.

I have seen this happens when the entity contains an attribute of JsonNode :/

Regarding to the stacktrace, I can share the whole debug logs from working version before to upgrade jackson and with jackson 2.17.0. I have compare both logs to see any difference related to datastore but no clue yet what could be happening
[jackson-2_13_4.txt](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/files/14964733/jackson-2_13_4.txt)
[jackson-2_17_0.txt](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/files/14964734/jackson-2_17_0.txt)

Hope this help🙏

**Comment by suztomo** [comment]
Thank you for the stacktrace.

[jackson-2_17_0.txt](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/files/14964734/jackson-2_17_0.txt):

```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'demoService' defined in file [C:\Users\XXX\IdeaProjects\demo\target\classes\com\example\demo\service\DemoService.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'demoRepository' defined in com.example.demo.repository.DemoRepository defined in @EnableDatastoreRepositories declared on DatastoreRepositoriesAutoConfigureRegistrar.EnableDatastoreRepositoriesConfiguration: Type must not be null
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:795) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:237) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1355) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1192) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:962) ~[spring-context-6.1.5.jar:6.1.5]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624) ~[spring-context-6.1.5.jar:6.1.5]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.2.4.jar:3.2.4]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.2.4.jar:3.2.4]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.2.4.jar:3.2.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:334) ~[spring-boot-3.2.4.jar:3.2.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354) ~[spring-boot-3.2.4.jar:3.2.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-3.2.4.jar:3.2.4]
	at com.example.demo.DemoApplication.main(DemoApplication.java:10) ~[classes/:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'demoRepository' defined in com.example.demo.repository.DemoRepository defined in @EnableDatastoreRepositories declared on DatastoreRepositoriesAutoConfigureRegistrar.EnableDatastoreRepositoriesConfiguration: Type must not be null
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:600) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1443) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:904) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:782) ~[spring-beans-6.1.5.jar:6.1.5]
	... 19 common frames omitted
Caused by: java.lang.IllegalArgumentException: Type must not be null
	at org.springframework.util.Assert.notNull(Assert.java:172) ~[spring-core-6.1.5.jar:6.1.5]
	at org.springframework.data.util.TypeInformation.of(TypeInformation.java:75) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:205) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at com.google.cloud.spring.data.datastore.core.mapping.DatastorePersistentEntityImpl.addEntityToDiscriminationFamily(DatastorePersistentEntityImpl.java:170) ~[spring-cloud-gcp-data-datastore-5.1.2.jar:5.1.2]
	at com.google.cloud.spring.data.datastore.core.mapping.DatastorePersistentEntityImpl.verify(DatastorePersistentEntityImpl.java:144) ~[spring-cloud-gcp-data-datastore-5.1.2.jar:5.1.2]
	at org.springframework.data.mapping.context.AbstractMappingContext.doAddPersistentEntity(AbstractMappingContext.java:431) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:383) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.lambda$createAndRegisterProperty$3(AbstractMappingContext.java:627) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.createAndRegisterProperty(AbstractMappingContext.java:624) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:578) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:728) ~[spring-core-6.1.5.jar:6.1.5]
	at org.springframework.data.mapping.context.AbstractMappingContext.doAddPersistentEntity(AbstractMappingContext.java:427) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:383) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:279) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:205) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at com.google.cloud.spring.data.datastore.core.mapping.DatastorePersistentEntityImpl.initializeSubclassEntities(DatastorePersistentEntityImpl.java:259) ~[spring-cloud-gcp-data-datastore-5.1.2.jar:5.1.2]
	at com.google.cloud.spring.data.datastore.core.mapping.DatastorePersistentEntityImpl.verify(DatastorePersistentEntityImpl.java:143) ~[spring-cloud-gcp-data-datastore-5.1.2.jar:5.1.2]
	at org.springframework.data.mapping.context.AbstractMappingContext.doAddPersistentEntity(AbstractMappingContext.java:431) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:383) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.lambda$createAndRegisterProperty$3(AbstractMappingContext.java:627) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.createAndRegisterProperty(AbstractMappingContext.java:624) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:578) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:728) ~[spring-core-6.1.5.jar:6.1.5]
	at org.springframework.data.mapping.context.AbstractMappingContext.doAddPersistentEntity(AbstractMappingContext.java:427) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:383) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.lambda$createAndRegisterProperty$3(AbstractMappingContext.java:627) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.createAndRegisterProperty(AbstractMappingContext.java:624) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:578) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:728) ~[spring-core-6.1.5.jar:6.1.5]
	at org.springframework.data.mapping.context.AbstractMappingContext.doAddPersistentEntity(AbstractMappingContext.java:427) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:383) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.lambda$createAndRegisterProperty$3(AbstractMappingContext.java:627) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.createAndRegisterProperty(AbstractMappingContext.java:624) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:578) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:728) ~[spring-core-6.1.5.jar:6.1.5]
	at org.springframework.data.mapping.context.AbstractMappingContext.doAddPersistentEntity(AbstractMappingContext.java:427) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:383) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:279) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:205) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at com.google.cloud.spring.data.datastore.core.mapping.DatastorePersistentEntityImpl.initializeSubclassEntities(DatastorePersistentEntityImpl.java:259) ~[spring-cloud-gcp-data-datastore-5.1.2.jar:5.1.2]
	at com.google.cloud.spring.data.datastore.core.mapping.DatastorePersistentEntityImpl.verify(DatastorePersistentEntityImpl.java:143) ~[spring-cloud-gcp-data-datastore-5.1.2.jar:5.1.2]
	at org.springframework.data.mapping.context.AbstractMappingContext.doAddPersistentEntity(AbstractMappingContext.java:431) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:383) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:279) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:205) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at com.google.cloud.spring.data.datastore.core.mapping.DatastorePersistentEntityImpl.addEntityToDiscriminationFamily(DatastorePersistentEntityImpl.java:170) ~[spring-cloud-gcp-data-datastore-5.1.2.jar:5.1.2]
	at com.google.cloud.spring.data.datastore.core.mapping.DatastorePersistentEntityImpl.verify(DatastorePersistentEntityImpl.java:144) ~[spring-cloud-gcp-data-datastore-5.1.2.jar:5.1.2]
	at org.springframework.data.mapping.context.AbstractMappingContext.doAddPersistentEntity(AbstractMappingContext.java:431) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:383) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.lambda$createAndRegisterProperty$3(AbstractMappingContext.java:627) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.createAndRegisterProperty(AbstractMappingContext.java:624) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:578) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:728) ~[spring-core-6.1.5.jar:6.1.5]
	at org.springframework.data.mapping.context.AbstractMappingContext.doAddPersistentEntity(AbstractMappingContext.java:427) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:383) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:279) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:205) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:92) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$6(RepositoryFactoryBeanSupport.java:282) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[na:na]
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:282) ~[spring-data-commons-3.2.4.jar:3.2.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1833) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782) ~[spring-beans-6.1.5.jar:6.1.5]
	... 30 common frames omitted
```

**Comment by meltsufin** [comment]
`JsonNode` is not one of the [supported types](https://googlecloudplatform.github.io/spring-cloud-gcp/5.1.2/reference/html/index.html#supported-types-2) in Spring Data Datastore. So, there must be some conversion going on. What is the actual data type you are using in Datastore? You can try registering your own converter as described in the documentation.

**Comment by jevanio** [comment]
@suztomo has the stacktrace helped to identify the cause?

**Comment by meltsufin** [comment]
@jevanio What's the last version of Spring Boot / Spring Cloud / Spring Cloud GCP that your project worked with?

**Comment by meltsufin** [comment]
@jevanio If you annotate `private JsonNode node` with `@Transient` and create a converter for `Pojo`, it seems to work.

**Comment by meltsufin** [comment]
@mp911de Do you have any insight into why this might be happening?

**Comment by meltsufin** [comment]
Asked related questions: https://github.com/spring-projects/spring-data-commons/issues/3085

**Comment by mp911de** [comment]
`DatastorePersistentEntityImpl.addEntityToDiscriminationFamily(DatastorePersistentEntityImpl.java:170)` is passing on a `null` value for the `Class` argument in `MappingContext.getPersistentEntity(…)`. If JsonNode is considered a store-native type, then you must not call `getPersistentEntity(…)` for it, instead, `CustomConversions.isSimpleType(…)` provides whether a type is considered a simple (store-native) one.

**Comment by meltsufin** [comment]
@mp911de This is very helpful because we can fix the problem by checking for `null` at `DatastorePersistentEntityImpl.addEntityToDiscriminationFamily(DatastorePersistentEntityImpl.java:170)`. However, I'm still not sure how to prevent entities from being created for `JsonNode` or other convertible types. Should we override `CustomConversion.isSimpleType()` in our `DatastoreCustomConversions` class?

**Comment by mp911de** [comment]
> Should we override CustomConversion.isSimpleType() in our DatastoreCustomConversions class?

You can address this issue by creating a `SimpleTypeHolder` that defines the types that are considered simple ones. Then, you pass on that `SimpleTypeHolder` instance to `CustomConversion ` (see Mongo and Cassandra examples from my previous comment).

**Comment by meltsufin** [comment]
I tried that but by the time `AbstractMappingContext.shouldCreatePersistentEntityFor()` is called, `AbstractMappingContext.simpleTypeHolder` has the custom types marked as not simple. I might need to dig further.

**Comment by jevanio** [comment]
Hey Folks,
As you mention, looks like including the transient help this demo service to start.
Which could be the impact of marking this JsonNode as transient?
