### ISSUE TITLE
Flaky GoogleStorageIntegrationTests 404 Not Found

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/spring-cloud-gcp#2875]
```
14:43:43:515 [INFO] Running com.google.cloud.spring.storage.it.GoogleStorageIntegrationTests
Error: 6:697 [ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.169 s <<< FAILURE! -- in com.google.cloud.spring.storage.it.GoogleStorageIntegrationTests
Error: 6:697 [ERROR] com.google.cloud.spring.storage.it.GoogleStorageIntegrationTests.createWithContent -- Time elapsed: 1.840 s <<< ERROR!
java.io.IOException: 
com.google.cloud.storage.StorageException: 404 Not Found
GET https://storage.googleapis.com/download/storage/v1/b/integration-spring-cloud-gcp/o/integration-test?alt=media&generation=1715525025722211
No such object: integration-spring-cloud-gcp/integration-test
	at com.google.cloud.storage.BaseStorageReadChannel.read(BaseStorageReadChannel.java:118)
	at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
	at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:107)
	at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:101)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:270)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:313)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:177)
	at java.base/java.io.Reader.read(Reader.java:250)
	at org.springframework.util.StreamUtils.copyToString(StreamUtils.java:85)
	at com.google.cloud.spring.storage.it.GoogleStorageIntegrationTests.createWithContent(GoogleStorageIntegrationTests.java:110)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: com.google.cloud.storage.StorageException: 404 Not Found
```

https://github.com/GoogleCloudPlatform/spring-cloud-gcp/actions/runs/9052153559/job/24869503044?pr=2874

**Comment by zhumin8** [comment]
closing as we have not observed it in the past few months.
