### ISSUE TITLE
Spring boot 3.3.0 compatibility issue with cloud-trace - zipkin / brave tracing error on startup

### ISSUE THREAD

**Issue by ashishsinghTW** [GoogleCloudPlatform/spring-cloud-gcp#2917]
I recently upgraded to springboot v3.3, after which the app is failing during startup. Service is hosted on gcp. Error:

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate 
[zipkin2.reporter.AsyncReporter]: Factory method 'stackdriverReporter' threw exception with message: Receiver class
zipkin2.reporter.stackdriver.StackdriverSender does not define or inherit an implementation of the resolved method 'abstract zipkin2.reporter.Encoding encoding()' 
of interface zipkin2.reporter.BytesMessageSender.
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:177)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:644)
	... 142 common frames omitted
Caused by: java.lang.AbstractMethodError: Receiver class zipkin2.reporter.stackdriver.StackdriverSender 
does not define or inherit an implementation of the resolved method 'abstract zipkin2.reporter.Encoding encoding()' 
of interface zipkin2.reporter.BytesMessageSender.
	at zipkin2.reporter.AsyncReporter$Builder.<init>(AsyncReporter.java:104)
	at zipkin2.reporter.AsyncReporter.builder(AsyncReporter.java:64)
	at zipkin2.reporter.AsyncReporter.builder(AsyncReporter.java:59)
	at com.google.cloud.spring.autoconfigure.trace.StackdriverTraceAutoConfiguration.stackdriverReporter(StackdriverTraceAutoConfiguration.java:178)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:140)
	... 143 common frames omitted
```

 I am using following tracing dependencies:
```
  implementation 'com.google.cloud:spring-cloud-gcp-starter-trace:5.3.0'
  implementation 'io.micrometer:micrometer-tracing-bridge-brave:1.3.0'
  implementation 'com.google.cloud:spring-cloud-gcp-starter-metrics':5.3.0
```

Any idea on why this might be happening ?

**Comment by meltsufin** [comment]
The project hasn't been upgraded to support Spring Boot 3.3 yet. The upgrade PR #2910 is pending.
cc: @burkedavison

**Comment by dkwakkel** [comment]
Ran into same, is there a workaround or eta?

**Comment by burkedavison** [comment]
We are working the upgrade to Spring Boot 3.3, but do not yet have a firm ETA.

**Comment by ccudennec-otto** [comment]
If I'm not mistaken you need to update zipkin-gcp, compare: https://github.com/openzipkin/zipkin-gcp/releases/tag/2.2.4

**Comment by salindah** [comment]
Any update on this issue ? I observed that the linked MR has been auto closed. This actually prevent us using latests features Spring GraphQL 1.3.1. Appreciate any update on this issue.

**Comment by burkedavison** [comment]
The next 5.5.0 release (due within the next few days) will have a fix for this issue.
