### ISSUE TITLE
Consistent alloydb integration test authentication issues

### ISSUE THREAD

**Issue by burkedavison** [GoogleCloudPlatform/spring-cloud-gcp#2988]
Example of integration tests failing with credentials problems:
https://github.com/GoogleCloudPlatform/spring-cloud-gcp/actions/runs/9649922009/job/26614418186?pr=2977
```
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:84)
	at org.springframework.jdbc.datasource.init.DatabasePopulatorUtils.execute(DatabasePopulatorUtils.java:52)
	... 63 more
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
```

Also witnessed in now-closed PR: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/2923

**Comment by meltsufin** [comment]
I don't think this is specific to alloydb. I see that cloudsql tests are failing too. This probably has to do with the db password being rotated.

**Comment by ttosta-google** [comment]
yeah the AlloyDB tests use the same password as the other databases (https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/759c616fb38fc669616605b8830c4d9a7087403c/.github/workflows/integrationTests.yaml#L92).

**Comment by meltsufin** [comment]
It should be fixed now.
