### ISSUE TITLE
Generator StackOverflow on mvn install

### ISSUE THREAD

**Issue by burkedavison** [GoogleCloudPlatform/spring-cloud-gcp#3005]
Steps to replicate:
* In the root folder: `mvn install -T 1C -DskipTests -Denforcer.skip -Dclirr.skip -Dcheckstyle.skip`
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.781 s
[INFO] Finished at: 2024-06-27T15:02:14-04:00
[INFO] ------------------------------------------------------------------------
---------------------------------------------------
constituent[0]: file:/Users/burkedavison/.sdkman/candidates/maven/current/conf/logging/
constituent[1]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/maven-builder-support-3.8.6.jar
constituent[2]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/maven-resolver-util-1.6.3.jar
constituent[3]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/plexus-component-annotations-2.1.0.jar
constituent[4]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/plexus-sec-dispatcher-2.0.jar
constituent[5]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/slf4j-api-1.7.36.jar
constituent[6]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/maven-resolver-spi-1.6.3.jar
constituent[7]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/plexus-utils-3.3.1.jar
constituent[8]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/plexus-interpolation-1.26.jar
constituent[9]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/maven-core-3.8.6.jar
constituent[10]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/maven-embedder-3.8.6.jar
constituent[11]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/plexus-cipher-2.0.jar
constituent[12]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/maven-model-builder-3.8.6.jar
constituent[13]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/javax.annotation-api-1.2.jar
constituent[14]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/maven-settings-3.8.6.jar
constituent[15]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/jcl-over-slf4j-1.7.36.jar
constituent[16]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/maven-model-3.8.6.jar
constituent[17]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/commons-cli-1.4.jar
constituent[18]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/maven-resolver-transport-wagon-1.6.3.jar
constituent[19]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/wagon-file-3.5.1.jar
constituent[20]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/maven-slf4j-provider-3.8.6.jar
constituent[21]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/org.eclipse.sisu.inject-0.3.5.jar
constituent[22]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/maven-artifact-3.8.6.jar
constituent[23]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/maven-resolver-provider-3.8.6.jar
constituent[24]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/commons-io-2.6.jar
constituent[25]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/wagon-http-3.5.1-shaded.jar
constituent[26]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/maven-repository-metadata-3.8.6.jar
constituent[27]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/maven-resolver-connector-basic-1.6.3.jar
constituent[28]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/maven-resolver-api-1.6.3.jar
constituent[29]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/maven-shared-utils-3.3.4.jar
constituent[30]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/maven-settings-builder-3.8.6.jar
constituent[31]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/org.eclipse.sisu.plexus-0.3.5.jar
constituent[32]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/wagon-provider-api-3.5.1.jar
constituent[33]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/maven-plugin-api-3.8.6.jar
constituent[34]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/maven-compat-3.8.6.jar
constituent[35]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/guice-4.2.2-no_aop.jar
constituent[36]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/maven-resolver-impl-1.6.3.jar
constituent[37]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/javax.inject-1.jar
constituent[38]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/commons-lang3-3.8.1.jar
constituent[39]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/jansi-2.4.0.jar
constituent[40]: file:/Users/burkedavison/.sdkman/candidates/maven/current/lib/guava-25.1-android.jar
---------------------------------------------------
Exception in thread "main" java.lang.StackOverflowError
        at java.base/java.nio.ByteBuffer.position(ByteBuffer.java:1551)
        at java.base/java.nio.ByteBuffer.position(ByteBuffer.java:285)
        at java.base/sun.nio.cs.UTF_8.updatePositions(UTF_8.java:83)
        at java.base/sun.nio.cs.UTF_8$Encoder.encodeArrayLoop(UTF_8.java:463)
        at java.base/sun.nio.cs.UTF_8$Encoder.encodeLoop(UTF_8.java:564)
        at java.base/java.nio.charset.CharsetEncoder.encode(CharsetEncoder.java:586)
        at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:370)
        at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:357)
        at java.base/sun.nio.cs.StreamEncoder.lockedWrite(StreamEncoder.java:158)
        at java.base/sun.nio.cs.StreamEncoder.write(StreamEncoder.java:139)
        at java.base/java.io.OutputStreamWriter.write(OutputStreamWriter.java:219)
        at java.base/java.io.BufferedWriter.implFlushBuffer(BufferedWriter.java:178)
        at java.base/java.io.BufferedWriter.flushBuffer(BufferedWriter.java:163)
        at java.base/java.io.PrintStream.implWrite(PrintStream.java:811)
        at java.base/java.io.PrintStream.write(PrintStream.java:796)
        at java.base/java.io.PrintStream.print(PrintStream.java:1002)
        at java.base/java.io.PrintStream.println(PrintStream.java:1171)
        at org.slf4j.impl.SimpleLogger.write(SimpleLogger.java:341)
        at org.slf4j.impl.SimpleLogger.log(SimpleLogger.java:310)
        at org.slf4j.impl.SimpleLogger.info(SimpleLogger.java:504)
        at org.apache.maven.cli.logging.Slf4jLogger.info(Slf4jLogger.java:59)
        at org.codehaus.plexus.archiver.AbstractArchiver$1.hasNext(AbstractArchiver.java:464)
        at org.codehaus.plexus.archiver.AbstractArchiver$1.hasNext(AbstractArchiver.java:467)
        at org.codehaus.plexus.archiver.AbstractArchiver$1.hasNext(AbstractArchiver.java:467)
        at org.codehaus.plexus.archiver.AbstractArchiver$1.hasNext(AbstractArchiver.java:467)
        at org.codehaus.plexus.archiver.AbstractArchiver$1.hasNext(AbstractArchiver.java:467)
        at org.codehaus.plexus.archiver.AbstractArchiver$1.hasNext(AbstractArchiver.java:467)
        at org.codehaus.plexus.archiver.AbstractArchiver$1.hasNext(AbstractArchiver.java:467)
        // ... repeat many many times ...
```

**Comment by blakeli0** [comment]
Bump to P1 as it is [blocking the release](https://fusion2.corp.google.com/ci/kokoro/prod:cloud-java-frameworks%2Fspring-cloud-gcp%2Fstage/activity/99c5bf0f-55cc-4e52-9fb9-5e4542672f0d/log) now.

**Comment by diegomarquezp** [comment]
Confirmed it occurs with `maven 3.8.6`
If I `sdk use maven 3.9.2` there is no StackOverflowError

**Comment by diegomarquezp** [comment]
The fix is to use `./mvnw`. We recently fixed the release scripts by doing this in https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/3015 and confirmed that `stage.sh` was successful.
Pending: investigate release notes of Maven and Maven Assembly Plugin to see why Maven 3.9 doesn't produce this error.

**Comment by diegomarquezp** [comment]
The usage of `/.mvnw` is the fix of the issue.
