### ISSUE TITLE
Cloud Trace - Zipkin Reporter issue on Spring Boot 3.3.2 

### ISSUE THREAD

**Issue by rangemasterd** [GoogleCloudPlatform/spring-cloud-gcp#3180]
Hello! After upgrading to Spring Boot v3.3.2 i noticed an error on the logs regarding Zipkin reporter

The error seems to appear always after a new app deployment and randomly during its execution time.

Error:
```
Unexpected error flushing spans
Exception in thread "AsyncReporter{StackdriverSender{projects/my-project}}" java.lang.NullPointerException: Cannot invoke "String.length()" because "ipString" is null
	at com.google.common.net.InetAddresses.ipStringToBytes(InetAddresses.java:196)
	at com.google.common.net.InetAddresses.forString(InetAddresses.java:158)
	at zipkin2.reporter.stackdriver.brave.AttributesExtractor.extract(AttributesExtractor.java:76)
	at zipkin2.reporter.stackdriver.brave.SpanTranslator.translate(SpanTranslator.java:80)
	at zipkin2.reporter.stackdriver.brave.StackdriverV2Encoder.translate(StackdriverV2Encoder.java:59)
	at zipkin2.reporter.stackdriver.brave.StackdriverV2Encoder.sizeInBytes(StackdriverV2Encoder.java:31)
	at zipkin2.reporter.stackdriver.brave.StackdriverV2Encoder.sizeInBytes(StackdriverV2Encoder.java:15)
	at zipkin2.reporter.internal.CountBoundedQueue.doDrain(CountBoundedQueue.java:115)
	at zipkin2.reporter.internal.CountBoundedQueue.drainTo(CountBoundedQueue.java:83)
	at zipkin2.reporter.internal.AsyncReporter$BoundedAsyncReporter.flush(AsyncReporter.java:241)
	at zipkin2.reporter.internal.AsyncReporter$Flusher.run(AsyncReporter.java:352)
	at java.base/java.lang.Thread.run(Unknown Source)
```

App Detail

- Java: 17
- Spring cloud gpc version: 5.5.1
- Spring boot version: 3.3.2

The app is deployed in GKE.

Any clue on why this might be happening?

**Comment by hjed** [comment]
This issue has been found and fixed in openzipkin-gcp https://github.com/openzipkin/zipkin-gcp/issues/224 would be good if dependency could be fixed in spring-cloud-gcp though
