### ISSUE TITLE
Spanner: Flaky Test: SpannerStatementQueryExecutor.getChildrenRowsQuery

### ISSUE THREAD

**Issue by williamlin0825** [GoogleCloudPlatform/spring-cloud-gcp#3290]
A test in the getChildrenRowsQueryTest checks for the result from getSQL() from SpannerStatementQueryExecutor.getChildrenRowsQuery. However, it checks the result in a specific order, which is not guaranteed. I purpose to simply check whether the selected field names are correct instead of checking in a specific order.

https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/05ad3efab8b70f2235e63f98dec3bc7e35f00954/spring-cloud-gcp-data-spanner/src/test/java/com/google/cloud/spring/data/spanner/repository/query/SpannerQueryLookupStrategyTests.java#L176-L179

```
[INFO] 
INFO: Adding excluded groups to newly created one
INFO: Adding NonDex argLine to existing argLine specified by the project
CONFIG: nondexFilter=.*
nondexMode=FULL
nondexSeed=933178
nondexStart=0
nondexEnd=9223372036854775807
nondexPrintstack=false
nondexDir=/home/jhihwei2/spring-cloud-gcp/spring-cloud-gcp-data-spanner/.nondex
nondexJarDir=/home/jhihwei2/spring-cloud-gcp/spring-cloud-gcp-data-spanner/.nondex
nondexExecid=fBBMREC82yfCbEu7MM71JCaMC87SgB9c1lrSr1Wi5nY=
nondexLogging=CONFIG
test=
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.google.cloud.spring.data.spanner.repository.query.SpannerQueryLookupStrategyTests
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.198 s <<< FAILURE! -- in com.google.cloud.spring.data.spanner.repository.query.SpannerQueryLookupStrategyTests
[ERROR] com.google.cloud.spring.data.spanner.repository.query.SpannerQueryLookupStrategyTests.getChildrenRowsQueryTest -- Time elapsed: 3.119 s <<< FAILURE!
org.opentest4j.AssertionFailedError: 

expected: "SELECT deleted, id3, id, id_2 FROM child_test_table WHERE ((id = @tag0 AND id_2 = @tag1)) AND (deleted = false)"
 but was: "SELECT id_2, id, id3, deleted FROM child_test_table WHERE ((id = @tag0 AND id_2 = @tag1)) AND (deleted = false)"
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at com.google.cloud.spring.data.spanner.repository.query.SpannerQueryLookupStrategyTests.getChildrenRowsQueryTest(SpannerQueryLookupStrategyTests.java:177)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   SpannerQueryLookupStrategyTests.getChildrenRowsQueryTest:177 
expected: "SELECT deleted, id3, id, id_2 FROM child_test_table WHERE ((id = @tag0 AND id_2 = @tag1)) AND (deleted = false)"
 but was: "SELECT id_2, id, id3, deleted FROM child_test_table WHERE ((id = @tag0 AND id_2 = @tag1)) AND (deleted = false)"
[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by mpeddada1** [comment]
Thank you for filing this issue. We've run this test extensively (1000 times) and haven't been able to reproduce the flaky behavior. Closing the issue at this time but please feel free to reopen if this problem persists.
