### ISSUE TITLE
pubsub-emulator integration test fails with "Invalid DNS name: ::1:8404"

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/spring-cloud-gcp#411]
**Describe the bug**

When I tried to run the integration test for "pubsub-emulator" in a ARM machine, it failed with "Invalid DNS name: ::1:8404".
 I think it's more about IPv6 issue rather than ARM-related problem.

Do you know how to resolve the problem? 

## Step 1: Start pubsub emulator

```
~/suztomo/spring-cloud-gcp$ gcloud beta emulators pubsub start --project=spring-cloud-gcp-ci
Executing: /usr/lib/google-cloud-sdk/platform/pubsub-emulator/bin/cloud-pubsub-emulator --host=localhost --port=8085
[pubsub] This is the Google Pub/Sub fake.
[pubsub] Implementation may be incomplete or differ from the real system.
[pubsub] Mar 25, 2021 6:07:37 PM com.google.cloud.pubsub.testing.v1.Main main
[pubsub] INFO: IAM integration is disabled. IAM policy methods and ACL checks are not supported
[pubsub] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[pubsub] SLF4J: Defaulting to no-operation (NOP) logger implementation
[pubsub] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[pubsub] Mar 25, 2021 6:07:37 PM com.google.cloud.pubsub.testing.v1.Main main
[pubsub] INFO: Server started, listening on 8085
```

## Step 2: Run the integration test

In another terminal, I ran the integration test of pubsub-emulator:

```
~/suztomo/spring-cloud-gcp$ IT=pubsub-emulator; ./mvnw   --batch-mode   --activate-profiles spring-cloud-gcp-ci-it \
    --define maven.javadoc.skip=true   --define skip.surefire.tests=true   --define it.${IT}=true    verify
```

It failed:

```
[INFO] --- maven-failsafe-plugin:2.22.1:integration-test (default) @ spring-cloud-gcp-pubsub-stream-binder ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.google.cloud.spring.stream.binder.pubsub.PubSubMessageChannelBinderEmulatorIntegrationTests
18:09:45.145 [main] INFO  c.g.c.s.s.b.pubsub.PubSubEmulator - Found emulator process to kill: 3482
18:09:45.147 [main] INFO  c.g.c.s.s.b.pubsub.PubSubEmulator - Found emulator process to kill: 3496
[ERROR] Tests run: 9, Failures: 0, Errors: 7, Skipped: 1, Time elapsed: 1.756 s <<< FAILURE! - in com.google.cloud.spring.stream.binder.pubsub.PubSubMessageChannelBinderEmulatorIntegrationTests
[ERROR] testSendAndReceiveMultipleTopics  Time elapsed: 0.38 s  <<< ERROR!
java.lang.IllegalArgumentException: Invalid DNS name: ::1:8404
	at com.google.cloud.spring.stream.binder.pubsub.PubSubMessageChannelBinderEmulatorIntegrationTests.getBinder(PubSubMessageChannelBinderEmulatorIntegrationTests.java:51)
	at com.google.cloud.spring.stream.binder.pubsub.PubSubMessageChannelBinderEmulatorIntegrationTests.getBinder(PubSubMessageChannelBinderEmulatorIntegrationTests.java:39)

[ERROR] testSendPojoReceivePojoWithStreamListener  Time elapsed: 0.049 s  <<< ERROR!
java.lang.IllegalArgumentException: Invalid DNS name: ::1:8404
	at com.google.cloud.spring.stream.binder.pubsub.PubSubMessageChannelBinderEmulatorIntegrationTests.getBinder(PubSubMessageChannelBinderEmulatorIntegrationTests.java:51)
	at com.google.cloud.spring.stream.binder.pubsub.PubSubMessageChannelBinderEmulatorIntegrationTests.getBinder(PubSubMessageChannelBinderEmulatorIntegrationTests.java:39)

[ERROR] testSendAndReceiveNoOriginalContentType  Time elapsed: 0.002 s  <<< ERROR!
java.lang.IllegalArgumentException: Invalid DNS name: ::1:8404
	at com.google.cloud.spring.stream.binder.pubsub.PubSubMessageChannelBinderEmulatorIntegrationTests.getBinder(PubSubMessageChannelBinderEmulatorIntegrationTests.java:51)
	at com.google.cloud.spring.stream.binder.pubsub.PubSubMessageChannelBinderEmulatorIntegrationTests.getBinder(PubSubMessageChannelBinderEmulatorIntegrationTests.java:39)

[ERROR] testSendAndReceive  Time elapsed: 0.002 s  <<< ERROR!
java.lang.IllegalArgumentException: Invalid DNS name: ::1:8404
	at com.google.cloud.spring.stream.binder.pubsub.PubSubMessageChannelBinderEmulatorIntegrationTests.getBinder(PubSubMessageChannelBinderEmulatorIntegrationTests.java:51)
	at com.google.cloud.spring.stream.binder.pubsub.PubSubMessageChannelBinderEmulatorIntegrationTests.getBinder(PubSubMessageChannelBinderEmulatorIntegrationTests.java:39)

[ERROR] testSendJsonReceiveJsonWithStreamListener  Time elapsed: 0.002 s  <<< ERROR!
java.lang.IllegalArgumentException: Invalid DNS name: ::1:8404
	at com.google.cloud.spring.stream.binder.pubsub.PubSubMessageChannelBinderEmulatorIntegrationTests.getBinder(PubSubMessageChannelBinderEmulatorIntegrationTests.java:51)
	at com.google.cloud.spring.stream.binder.pubsub.PubSubMessageChannelBinderEmulatorIntegrationTests.getBinder(PubSubMessageChannelBinderEmulatorIntegrationTests.java:39)

[ERROR] testSendJsonReceivePojoWithStreamListener  Time elapsed: 0.002 s  <<< ERROR!
java.lang.IllegalArgumentException: Invalid DNS name: ::1:8404
	at com.google.cloud.spring.stream.binder.pubsub.PubSubMessageChannelBinderEmulatorIntegrationTests.getBinder(PubSubMessageChannelBinderEmulatorIntegrationTests.java:51)
	at com.google.cloud.spring.stream.binder.pubsub.PubSubMessageChannelBinderEmulatorIntegrationTests.getBinder(PubSubMessageChannelBinderEmulatorIntegrationTests.java:39)

[ERROR] testSendPojoReceivePojoWithStreamListenerDefaultContentType  Time elapsed: 0.002 s  <<< ERROR!
java.lang.IllegalArgumentException: Invalid DNS name: ::1:8404
	at com.google.cloud.spring.stream.binder.pubsub.PubSubMessageChannelBinderEmulatorIntegrationTests.getBinder(PubSubMessageChannelBinderEmulatorIntegrationTests.java:51)
	at com.google.cloud.spring.stream.binder.pubsub.PubSubMessageChannelBinderEmulatorIntegrationTests.getBinder(PubSubMessageChannelBinderEmulatorIntegrationTests.java:39)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   PubSubMessageChannelBinderEmulatorIntegrationTests>AbstractBinderTests.testSendAndReceive:173->getBinder:39->getBinder:51 » IllegalArgument
[ERROR]   PubSubMessageChannelBinderEmulatorIntegrationTests>AbstractBinderTests.testSendAndReceiveMultipleTopics:220->getBinder:39->getBinder:51 » IllegalArgument
[ERROR]   PubSubMessageChannelBinderEmulatorIntegrationTests>AbstractBinderTests.testSendAndReceiveNoOriginalContentType:286->getBinder:39->getBinder:51 » IllegalArgument
[ERROR]   PubSubMessageChannelBinderEmulatorIntegrationTests>AbstractBinderTests.testSendJsonReceiveJsonWithStreamListener:520->getBinder:39->getBinder:51 » IllegalArgument
[ERROR]   PubSubMessageChannelBinderEmulatorIntegrationTests>AbstractBinderTests.testSendJsonReceivePojoWithStreamListener:473->getBinder:39->getBinder:51 » IllegalArgument
[ERROR]   PubSubMessageChannelBinderEmulatorIntegrationTests>AbstractBinderTests.testSendPojoReceivePojoWithStreamListener:567->getBinder:39->getBinder:51 » IllegalArgument
[ERROR]   PubSubMessageChannelBinderEmulatorIntegrationTests>AbstractBinderTests.testSendPojoReceivePojoWithStreamListenerDefaultContentType:433->getBinder:39->getBinder:51 » IllegalArgument
[INFO] 
[ERROR] Tests run: 9, Failures: 0, Errors: 7, Skipped: 1
```

The content of /home/ubuntu/.config/gcloud/emulators/pubsub/env.yaml:

```
ubuntu@ip-172-31-2-167:~/suztomo/spring-cloud-gcp$ cat /home/ubuntu/.config/gcloud/emulators/pubsub/env.yaml
---
PUBSUB_EMULATOR_HOST: ::1:8518
```

**Sample**

The command above is the sample.

**Comment by elefeint** [comment]
Emulator integration tests start an emulator instance themselves -- you don't need to start one manually.
The error happened because an IPv6 address was assigned next, and some code in the stack does not know how to handle that.

The solution is to kill all running emulator processes, and to try the test again.

**Comment by suztomo** [comment]
It worked!
