### ISSUE TITLE
spring-cloud-gcp-starter-sql-postgresql example fails to run on AppEngine

### ISSUE THREAD

**Issue by ciferkey** [GoogleCloudPlatform/spring-cloud-gcp#430]
Spring boot version: 2.4.4
Spring Cloud verison: 2020.0.0
Spring Cloud GCP version: 2.0.2

Trying to use Spring Cloud GCP for postgresql based off the provided example but converted to work with Gradle: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples/spring-cloud-gcp-sql-postgres-sample

The following exception is throw during startup when run on AppEngine. It does not occur when run locally:

```
2021-04-05 04:19:52 default[1]  java.lang.IllegalStateException: Unable to set ApplicationName - SQLAdmin client already initialized.  
at com.google.cloud.sql.core.CoreSocketFactory.setApplicationName(CoreSocketFactory.java:408) ~[jdbc-socket-factory-core-1.2.1.jar:na]  
at com.google.cloud.spring.autoconfigure.sql.CloudSqlEnvironmentPostProcessor.postProcessEnvironment(CloudSqlEnvironmentPostProcessor.java:105) ~[spring-cloud-gcp-autoconfigure-2.0.2.jar:2.0.2]  
at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:100) ~[spring-boot-2.4.4.jar:2.4.4]  
at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:86) ~[spring-boot-2.4.4.jar:2.4.4]  
at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.5.jar:5.3.5]  
at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.5.jar:5.3.5]  
at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.5.jar:5.3.5]  
at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131) ~[spring-context-5.3.5.jar:5.3.5]  
at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:82) ~[spring-boot-2.4.4.jar:2.4.4]  
at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:63) ~[spring-boot-2.4.4.jar:2.4.4]  
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541) ~[na:na]  
at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117) ~[spring-boot-2.4.4.jar:2.4.4]  
at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111) ~[spring-boot-2.4.4.jar:2.4.4]  
at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:62) ~[spring-boot-2.4.4.jar:2.4.4]  
at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:362) ~[spring-boot-2.4.4.jar:2.4.4]  
at org.springframework.boot.SpringApplication.run(SpringApplication.java:320) ~[spring-boot-2.4.4.jar:2.4.4]  at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:173) ~[spring-boot-2.4.4.jar:2.4.4]  
at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:153) ~[spring-boot-2.4.4.jar:2.4.4]  
at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:95) ~[spring-boot-2.4.4.jar:2.4.4]  
at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:174) ~[spring-web-5.3.5.jar:5.3.5]  
at org.eclipse.jetty.plus.annotation.ContainerInitializer.callStartup(ContainerInitializer.java:142) ~[na:na]  
at org.eclipse.jetty.annotations.ServletContainerInitializersStarter.doStart(ServletContainerInitializersStarter.java:64) ~[na:na]  
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[na:na]  
at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:356) ~[na:na]  
at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1449) ~[na:na]  
at com.google.apphosting.runtime.jetty94.AppEngineWebAppContext.startWebapp(AppEngineWebAppContext.java:222) ~[na:na]  
at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1414) ~[na:na]  
at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:911) ~[na:na]  
at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288) ~[na:na]  
at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524) ~[na:na]  
at com.google.apphosting.runtime.jetty94.AppEngineWebAppContext.doStart(AppEngineWebAppContext.java:166) ~[na:na]  
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[na:na]  
at com.google.apphosting.runtime.jetty94.AppVersionHandlerMap.createHandler(AppVersionHandlerMap.java:209) ~[na:na]  
at com.google.apphosting.runtime.jetty94.AppVersionHandlerMap.getHandler(AppVersionHandlerMap.java:139) ~[na:na]  
at com.google.apphosting.runtime.jetty94.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:146) ~[na:na]  
at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest(JavaRuntime.java:782) ~[na:na]  
at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:745) ~[na:na]  
at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:715) ~[na:na]  
at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:261) ~[na:na]  
at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

Dependency section from build.gradle.kts:

```
extra["springCloudGcpVersion"] = "2.0.2"
extra["springCloudVersion"] = "2020.0.0"

dependencies {
	// GCP
	implementation("com.google.appengine:appengine-api-1.0-sdk:+")
	providedCompile("javax.servlet:javax.servlet-api:4.0.1")
	implementation("jstl:jstl:1.2")
	implementation("com.google.cloud:google-cloud-texttospeech:1.3.0")
	implementation("com.google.cloud:spring-cloud-gcp-starter")
	implementation("com.google.cloud:spring-cloud-gcp-starter-storage")
	implementation("com.google.cloud:spring-cloud-gcp-starter-sql-postgresql")
```

application.yml (with sensitive information removed).

```
spring:
  cloud:
    gcp:
      sql:
        instance-connection-name: <connection name>
        database-name: <database name>
  jpa:
    hibernate:
        ddl-auto: update
  datasource:
    username: <username>
    password: <password>
```

**Comment by elefeint** [comment]
Judging from `com.google.appengine:appengine-api-1.0-sdk` dependency, you are on AppEngine Standard, is that right?
I've tried deploying the current sample to both, Standard and Flex, and did not see this issue, even with the additional dependencies (`com.google.appengine:appengine-api-1.0-sdk`, `jstl:jstl`, `com.google.cloud:google-cloud-texttospeech`, `com.google.cloud:spring-cloud-gcp-starter-storage`).

Could you provide a complete reproducible application (without sensitive property values, of course)?

**Comment by ciferkey** [comment]
I've put together a minimal example.... but the minimal example does not exhibit the bug. I'm going to investigate further so I can send a working failing example.

**Comment by ciferkey** [comment]
It was a mistake in the configuration on my part not a bug in the library. Closing the issue.
