### ISSUE TITLE
Multiple function definition does not work in spring-cloud-function-adapter-gcp

### ISSUE THREAD

**Issue by pantbrajesh** [GoogleCloudPlatform/spring-cloud-gcp#450]
**Describe the bug**
I am creating a CRUD based application using spring cloud function keeping it vendor agnostic. So if we need to change the vendor we can just change the implementation logic and migrate it. Instead of having a tight coupling with vendor and business logic. For Curd operation I created 4 functions which does the job. But while running the application its only redirecting the request to single function.  

**Code Sample**
So i have Four functions
```
@Component
public class CreateEntityFunction implements Consumer<Message<IEntity>>

@Component
public class GetEntityFunction implements Function<Message<IEntity>, Message<IEntity>>

@Component
public class UpdateEntityFunction implements Consumer<Message<IEntity>> 

@Component
public class DeleteEntityFunction implements Consumer<Message<IEntity>> 
```
I have defined the function definition in application.properties file
`spring.cloud.function.definition= createEntityFunction|GetEntityFunction|UpdateEntityFunction|DeleteEntityFunction`

This is how the function is invoked
```
curl -X POST -H "Content-Type: application/json" http://localhost:8080/createDeviceEntityFunction -d '{
"serial" :"1234567",
"model" : "model1",
"type" : "type1"
}'
```

But when the function is called it takes first function and invoke it. Even if you change the calling name of the function to 
GetEntityFunction or UpdateEntityFunction
 
 Pom.xml
 ```
 <?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>org.example</groupId>
	<artifactId>device-cloud</artifactId>
	<version>1.0-SNAPSHOT</version>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.4.5</version>
		<relativePath /> <!-- lookup parent from repository -->
	</parent>

	<properties>
		<spring-cloud.version>3.1.2</spring-cloud.version>
		<wrapper.version>1.0.17.RELEASE</wrapper.version>
		<maven.compiler.source>11</maven.compiler.source>
		<maven.compiler.target>11</maven.compiler.target>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-function-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-function-adapter-gcp</artifactId>
			<version>3.1.3-SNAPSHOT</version>
		</dependency>


		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<version>42.2.19</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>com.zaxxer</groupId>
			<artifactId>HikariCP</artifactId>
			<version>4.0.3</version>
		</dependency>


	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>2020.0.0</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>


	<build>
		<finalName>${project.artifactId}</finalName>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>11</source>
					<target>11</target>
				</configuration>
			</plugin>


			<plugin>
				<artifactId>maven-deploy-plugin</artifactId>
				<version>2.8.2</version>
				<configuration>
					<skip>true</skip>
				</configuration>
			</plugin>


			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<outputDirectory>target/deploy</outputDirectory>
				</configuration>
				<dependencies>
					<dependency>
						<groupId>org.springframework.cloud</groupId>
						<artifactId>spring-cloud-function-adapter-gcp</artifactId>
						<version>${spring-cloud.version}</version>
					</dependency>
				</dependencies>
			</plugin>

			<!--add the the Function Maven plugin so you can run the function locally: -->
			<plugin>
				<groupId>com.google.cloud.functions</groupId>
				<artifactId>function-maven-plugin</artifactId>
				<version>0.9.2</version>
				<configuration>
					<functionTarget>function.DrsApplication</functionTarget>
				</configuration>
			</plugin>

			<plugin>
				<groupId>com.google.cloud.functions</groupId>
				<artifactId>function-maven-plugin</artifactId>
				<version>0.9.1</version>
				<configuration>
					<functionTarget>org.springframework.cloud.function.adapter.gcp.GcfJarLauncher</functionTarget>
					<port>8080</port>
				</configuration>
			</plugin>
			
		</plugins>
	</build>
	<repositories>
		<repository>
			<id>spring-snapshots</id>
			<name>Spring Snapshots</name>
			<url>https://repo.spring.io/libs-snapshot-local</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
			<releases>
				<enabled>false</enabled>
			</releases>
		</repository>
		<repository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/libs-milestone-local</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
		<repository>
			<id>spring-releases</id>
			<name>Spring Releases</name>
			<url>https://repo.spring.io/release</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
	</repositories>
	<pluginRepositories>
		<pluginRepository>
			<id>spring-snapshots</id>
			<name>Spring Snapshots</name>
			<url>https://repo.spring.io/libs-snapshot-local</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
			<releases>
				<enabled>false</enabled>
			</releases>
		</pluginRepository>
		<pluginRepository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/libs-milestone-local</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</pluginRepository>
		<pluginRepository>
			<id>spring-releases</id>
			<name>Spring Releases</name>
			<url>https://repo.spring.io/libs-release-local</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</pluginRepository>
	</pluginRepositories>
</project>
```
So to achieve i have to package single application 4 times with different function definition in application.properties

**Observations**
Since the entry point for GCP is 
`org.springframework.cloud.function.adapter.gcp.GcfJarLauncher`
After debugging I found that the requests are well received in the service method of the class and then its delegates the request to `org.springframework.cloud.function.adapter.gcp.FunctionInvoker`
and the desired function is looked for. This lookup function doesn't return the correct  the function, due to which the request is redirected to any function depending on lookup

**Comment by dzou** [comment]
I'll help take a look.

Can you try [using `;` in your function.definition](https://docs.spring.io/spring-cloud-function/docs/current/reference/html/spring-cloud-function.html#_function_filtering_rules) argument to see if that works? I.e. `spring.cloud.function.definition= createEntityFunction;GetEntityFunction;UpdateEntityFunction;DeleteEntityFunction`. I don't think using the `|` is right; that will chain your functions together and feed the output of one as input into the next.

If you could also share a small reproducible sample with us, that would be very helpful. You can use [this sample](https://github.com/spring-cloud/spring-cloud-function/tree/master/spring-cloud-function-samples/function-sample-gcp-http) as a starting point and modify it.

**Comment by pantbrajesh** [comment]
[drs-cloud.zip](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/files/6403387/drs-cloud.zip)
Attaching my sample code also will take a look at that example provided

**Comment by pantbrajesh** [comment]
I tried to create two functions in [this sample code](https://github.com/spring-cloud/spring-cloud-function/tree/master/spring-cloud-function-samples/function-sample-gcp-http) . When you have single function its working well. When you have multiple function definition its not able to do lookup for the right function name. Below is the exception which i get 

```
Apr 30, 2021 1:46:48 PM com.google.cloud.functions.invoker.NewHttpFunctionExecutor service
WARNING: Failed to execute org.springframework.cloud.function.adapter.gcp.GcfJarLauncher
java.lang.IllegalArgumentException: 'function' with name '' must not be null
	at org.springframework.util.Assert.notNull(Assert.java:201)
	at org.springframework.cloud.function.adapter.gcp.FunctionInvoker.lookupFunction(FunctionInvoker.java:78)
	at org.springframework.cloud.function.adapter.gcp.FunctionInvoker.service(FunctionInvoker.java:88)
	at org.springframework.cloud.function.adapter.gcp.GcfJarLauncher.service(GcfJarLauncher.java:53)
	at com.google.cloud.functions.invoker.NewHttpFunctionExecutor.service(NewHttpFunctionExecutor.java:65)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:755)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:547)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at com.google.cloud.functions.invoker.runner.Invoker$NotFoundHandler.handle(Invoker.java:397)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
Attaching the sample code
[function-sample-gcp-http.zip](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/files/6403901/function-sample-gcp-http.zip)

I have two beans created in main function
```
      @Bean (name="function")
	public Function<String, String> function() {
		return value -> value.toUpperCase();
	}

	@Bean (name="testFunction")
	public Function<String, String> testFunction() {
		return value -> value.toLowerCase();
	}
	```

**Comment by dzou** [comment]
Hey, thanks for sharing these samples. I did some more research and am working on a solution to support [URL path mapping to functions here](https://github.com/spring-cloud/spring-cloud-function/compare/master...dzou:multi-function-support?expand=1). I.e. mapping `localhost:8080/myfunction` --> the `myfunction` spring function.

I also did some more research on `spring.cloud.function.definition`. I'm not sure how this is supposed to be used, but it seems like you can use it to specify at run-time which function you want to use. First, delete the `application.properties` from your project. Then use this setting to specify the function at runtime:

This runs the `function()`:
```
mvn function:run -Dspring.cloud.function.definition=function
```

This runs the `testFunction()`:
```
mvn function:run -Dspring.cloud.function.definition=testFunction
```

You can have the same Java application run multiple functions by changing the `spring.cloud.function.definition` argument you pass to the app. This is the best that we can do right now. Unfortunately right now, we do not support mapping URL path to function bean lookup.

**Comment by pantbrajesh** [comment]
Thanks @dzou any road map to support mapping URL path to function bean lookup

**Comment by dzou** [comment]
Not sure about roadmap, I can try to submit a PR in the next couple of weeks. I'm not sure how long it will take because we would need to figure out whether this idea fits in the design of Spring cloud functions and GCF; this will require asking the project maintainer.

But before this, we first need submit a fix for the GCP adapter in the latest version: https://github.com/spring-cloud/spring-cloud-function/pull/693

**Comment by elefeint** [comment]
We don't currently have this usecase on the roadmap, but also Spring Cloud GCP is not the right location for the GCF adapter issues.
If you are still interested in the feature, please open a new issue in https://github.com/spring-cloud/spring-cloud-function
