### ISSUE TITLE
Current Pub/Sub healthcheck forces to add extra GCP permissions not needed for the services execution

### ISSUE THREAD

**Issue by rubasace** [GoogleCloudPlatform/spring-cloud-gcp#494]
From a security perspective, at my company, we try to assign to each service account the minimum number of permissions possible.  We have services using `PubSubTemplate` for two different use cases:
1) Subscribe to one or more topics and process data
2) Publish data to one or more topics

For the services that just publish, we assign the role `roles/pubsub.publisher` and for those who subscribe we assign the role `roles/pubsub.subscriber`. We assign both if the service performs both actions.

Currently, our problem is that services don't have enough permissions to create runtime subscriptions or even to read from them (publishers).  What we are experiencing is that the current `PubSubHealthIndicator` tries to create a new subscription at runtime without having the permission to do so, which makes the applications fail at startup due to a timeout on the health check.

I'm not sure about what the best solution is, currently I'm just providing an alternative `PubSubHealthIndicator` that just returns up in case of not having a specified topic for the health check, assuming that the applications that specify one do so because they are pre-provisioning it or have set up the right permissions in advance.

My concern is that the default behaviour of this health indicator is potentially forcing applications to run with a wider set of permissions than they need for their normal execution, which doesn't seem like a sensible approach.

**Comment by elefeint** [comment]
@rubasace As of version 2.0.2, `PubSubHealthIndicator` supports setting a custom healthcheck subscription through `spring.cloud.gcp.pubsub.health.subscription` property ([docs](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/docs/src/main/asciidoc/pubsub.adoc#cloud-pubsub-health-indicator)). When this property is set, "subscription not found" and "subscription not authorized" are no longer expected successful response codes. Health Indicator does not try to automatically create subscriptions (Spring Cloud Stream does, though -- if you use it, then turning autocreation off is likely a good idea for your architecture).

However, it sounds like your issue is that service accounts with only _publish_ permissions cannot do the _pull_ of messages required for the healthcheck operation. If you return UP in all cases for publisher-only applications, you may as well turn this health check off with `management.health.pubsub.enabled`. If you prefer to have a functioning healthcheck, my suggestion would be operational rather than programmatic: [Cloud Pub/Sub permissions](https://cloud.google.com/pubsub/docs/access-control) is on a per-subscription level, so creating a single global healthcheck subscription and granting publishers `pubsub.subscriptions.consume` on only that subscription would allow all of your services to perform health checks.

**Comment by rubasace** [comment]
@elefeint I'm providing this custom behaviour from an autoconfiguration in a common library, I do it this way so I can still respect the property if set, rather than simply disabling the health indicator. Otherwise, applications would have to reenable the health indicator on top of providing the topic name. 

If I'm understanding correctly, the health indicator will only fail on subscription not found when `spring.cloud.gcp.pubsub.health.subscription` is set, otherwise it will become an UP state.

> If you prefer to have a functioning healthcheck, my suggestion would be operational rather than programmatic: Cloud Pub/Sub permissions is on a per-subscription level, so creating a single global healthcheck subscription and granting publishers pubsub.subscriptions.consume on only that subscription would allow all of your services to perform health checks.

We will explore this approach as it sounds like the best way of solving it :)

**Comment by rubasace** [comment]
> it sounds like your issue is that service accounts with only publish permissions cannot do the pull of messages

Actually, we have applications with `pubsub.publisher` + `pubsub.subscriber` roles facing this issue. The exact error looks like this:

```
Caused by: org.springframework.beans.factory.BeanInitializationException: Validation of health indicator failed; nested exception is java.util.concurrent.TimeoutException
	at com.google.cloud.spring.autoconfigure.pubsub.health.PubSubHealthIndicator.validationFailed(PubSubHealthIndicator.java:169)
	at com.google.cloud.spring.autoconfigure.pubsub.health.PubSubHealthIndicator.doHealthCheck(PubSubHealthIndicator.java:139)
	at com.google.cloud.spring.autoconfigure.pubsub.health.PubSubHealthIndicator.validateHealthCheck(PubSubHealthIndicator.java:106)
	at com.google.cloud.spring.autoconfigure.pubsub.health.PubSubHealthIndicatorAutoConfiguration.createIndicator(PubSubHealthIndicatorAutoConfiguration.java:79)
	at com.google.cloud.spring.autoconfigure.pubsub.health.PubSubHealthIndicatorAutoConfiguration.createIndicator(PubSubHealthIndicatorAutoConfiguration.java:49)
	at org.springframework.boot.actuate.autoconfigure.health.AbstractCompositeHealthContributorConfiguration.createContributor(AbstractCompositeHealthContributorConfiguration.java:54)
	at com.google.cloud.spring.autoconfigure.pubsub.health.PubSubHealthIndicatorAutoConfiguration.pubSubHealthContributor(PubSubHealthIndicatorAutoConfiguration.java:69)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334)
Caused by: java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
	at org.springframework.util.concurrent.SettableListenableFuture.get(SettableListenableFuture.java:134)
	at com.google.cloud.spring.autoconfigure.pubsub.health.PubSubHealthIndicator.pullMessage(PubSubHealthIndicator.java:148)
	at com.google.cloud.spring.autoconfigure.pubsub.health.PubSubHealthIndicator.doHealthCheck(PubSubHealthIndicator.java:122)
	at com.google.cloud.spring.autoconfigure.pubsub.health.PubSubHealthIndicator.validateHealthCheck(PubSubHealthIndicator.java:106)
	at com.google.cloud.spring.autoconfigure.pubsub.health.PubSubHealthIndicatorAutoConfiguration.createIndicator(PubSubHealthIndicatorAutoConfiguration.java:79)
	at com.google.cloud.spring.autoconfigure.pubsub.health.PubSubHealthIndicatorAutoConfiguration.createIndicator(PubSubHealthIndicatorAutoConfiguration.java:49)
	at org.springframework.boot.actuate.autoconfigure.health.AbstractCompositeHealthContributorConfiguration.createContributor(AbstractCompositeHealthContributorConfiguration.java:54)
	at com.google.cloud.spring.autoconfigure.pubsub.health.PubSubHealthIndicatorAutoConfiguration.pubSubHealthContributor(PubSubHealthIndicatorAutoConfiguration.java:69)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
```

This is being initiated by the [create indicator](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/v2.0.2/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/pubsub/health/PubSubHealthIndicatorAutoConfiguration.java#L79) on the autoconfiguration, which seems to always fail [on timeouts](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/v2.0.2/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/pubsub/health/PubSubHealthIndicator.java#L127)

Assuming this application has reading permissions,  any idea why we would get this kind of timeouts?
