### ISSUE TITLE
Disabling Spring Cloud GCP Project ID

### ISSUE THREAD

**Issue by nverbeek** [GoogleCloudPlatform/spring-cloud-gcp#499]
I have an application that is utilizing Spring Cloud GCP. I use this for GCP logging only at this time. My issue revolves around the ability to disable this for local testing, debugging, and CI. My application has the requirement to run outside GCP and thus has multiple logback profiles - one that will use Spring Cloud GCP logging and others that are simpler.

What I'm experiencing is that when attempting to disable GCP logging, I fail to start up:

`A project ID is required for this service but could not be determined from the builder or the environment.  Please set a project ID using the builder.`

In my application.properties file, I've placed the following by default in attempt to disable GCP logging:

```
spring.cloud.gcp.project-id=fake-project-id
spring.cloud.gcp.core.enabled=false
spring.cloud.gcp.logging.enabled=false
spring.cloud.gcp.trace.enabled=false
```

In looking at the `ServiceOptions` class within the spring source code, I'm failing to see where the `spring.cloud.gcp.project-id` property is ever used. The code appears to depend completely on OS properties, environment variables and user configs. This is confusing, as the [documentation](https://cloud.spring.io/spring-cloud-gcp/single/spring-cloud-gcp.html#_project_id) states:

> If a `spring.cloud.gcp.project-id` property is specified, the provided `GcpProjectIdProvider` returns that property value.

Is there any way I can avoid this project ID issue? I realize that it is possible to set the `GOOGLE_CLOUD_PROJECT` environment variable, but that requires us to always set the environment variable even in environments where we have no need for GCP logging. I feel I must be missing something here that allows me to get around this. 

For reference, my logback-spring.xml:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <include resource="org/springframework/cloud/gcp/autoconfigure/logging/logback-appender.xml" />
    <springProperty scope="context" name="logDirectory" source="dematic.workflow.log-directory"/>
    <conversionRule conversionWord="clr" converterClass="org.springframework.boot.logging.logback.ColorConverter" />
    <conversionRule conversionWord="wex" converterClass="org.springframework.boot.logging.logback.WhitespaceThrowableProxyConverter" />
    <conversionRule conversionWord="wEx" converterClass="org.springframework.boot.logging.logback.ExtendedWhitespaceThrowableProxyConverter" />

    <appender name="STDOUT_SIMPLE" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <Pattern>
                %5p %-40.40logger{39} %m%n%wEx
            </Pattern>
        </encoder>
    </appender>

    <appender name="CONSOLE_JSON" class="ch.qos.logback.core.ConsoleAppender">
        <!-- GCP specific appender that uses StackDriver to print the logs -->
        <encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
            <layout class="org.springframework.cloud.gcp.logging.StackdriverJsonLayout"/>
        </encoder>
    </appender>

    <springProfile name="simple">
        <root level="INFO" additivity="false">
            <appender-ref ref="STDOUT_SIMPLE" />
        </root>
    </springProfile>

    <springProfile name="cloud_gcp">
        <root level="INFO" additivity="false">
            <appender-ref ref="CONSOLE_JSON" />
        </root>
    </springProfile>
</configuration>
```

By default, my `spring.profiles.active` is set to `simple`, and the other `application.properties` I put above are there by default. I'd expect with this configuration to have no GCP stuff loading. When I'm running in GCP, I override these properties to turn on GCP logging and in that case I set the `GOOGLE_CLOUD_PROJECT` env var.

My spring versions:

```xml
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-dependencies</artifactId>
            <version>2.3.3.RELEASE</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-gcp-dependencies</artifactId>
            <version>1.2.8.RELEASE</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
```

Any help you can provide on this would be much appreciated!

**Comment by meltsufin** [comment]
@nverbeek Can you provide some of the stacktrace that is causing the exception?
It's probably coming from the `com.google.cloud.spring.logging.LoggingAppender` which is loaded through this line in your logback config:
```
<include resource="org/springframework/cloud/gcp/autoconfigure/logging/logback-appender.xml" />
```
Since this is loading through logback rather than Spring Boot, I'm not sure we can really control it being enabled or disabled.
Maybe it's possible to avoid this include or have it inside a profile? Also, it might be possible to have a separate logback config file for each of the profiles.

**Comment by nverbeek** [comment]
Absolutely, here's the entire output:

```
java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.joran.spi.Interpreter@17:14 - RuntimeException in Action for tag [appender] java.lang.IllegalArgumentException: A project ID is required for this service but could not be determined from the builder or the environment.  Please set a project ID using the builder.
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:169)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:80)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:60)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:118)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:306)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:281)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:239)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:216)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:80)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:345)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at com.dematic.wcs.workflow.Application.main(Application.java:28)

Exception in thread "main" java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.joran.spi.Interpreter@17:14 - RuntimeException in Action for tag [appender] java.lang.IllegalArgumentException: A project ID is required for this service but could not be determined from the builder or the environment.  Please set a project ID using the builder.
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:169)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:80)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:60)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:118)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:306)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:281)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:239)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:216)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:80)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:345)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at com.dematic.wcs.workflow.Application.main(Application.java:28)

Process finished with exit code 1
```

**Comment by nverbeek** [comment]
@meltsufin Your comments pushed me to the right path. I made the following change to get everything happy:

From:
```xml
<include resource="org/springframework/cloud/gcp/autoconfigure/logging/logback-appender.xml" />

<appender name="CONSOLE_JSON" class="ch.qos.logback.core.ConsoleAppender">
    <!-- GCP specific appender that uses StackDriver to print the logs -->
    <!-- This results in metadata that allows GCP to know specifics about the logs -->
    <encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
        <layout class="org.springframework.cloud.gcp.logging.StackdriverJsonLayout"/>
    </encoder>
</appender>

<springProfile name="cloud_gcp">
    <root level="INFO" additivity="false">
        <appender-ref ref="CONSOLE_JSON" />
    </root>
</springProfile>
```

To:
```xml
<springProfile name="cloud_gcp">
    <include resource="org/springframework/cloud/gcp/autoconfigure/logging/logback-appender.xml" />
    <appender name="CONSOLE_JSON" class="ch.qos.logback.core.ConsoleAppender">
        <!-- GCP specific appender that uses StackDriver to print the logs -->
        <!-- This results in metadata that allows GCP to know specifics about the logs -->
        <encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
            <layout class="org.springframework.cloud.gcp.logging.StackdriverJsonLayout"/>
        </encoder>
    </appender>
    <root level="INFO" additivity="false">
        <appender-ref ref="CONSOLE_JSON" />
    </root>
</springProfile>
```

Moving the `appender` AND the `include` made it work. I had tried this approach previously, but never tried to move the `include` inside the profile definition. That was vital.

Thanks for the help!
