### ISSUE TITLE
pubSubHeathContributor timeout exception on SpringBoot 2.5.5 start up

### ISSUE THREAD

**Issue by michaelmok2021** [GoogleCloudPlatform/spring-cloud-gcp#648]
We are running on JDK 11 on Ubuntu and the app is a SpringBoot jar. 

```xml
  <spring-boot.version>2.5.5</spring-boot.version>
        <spring-cloud-gcp.version>2.0.4</spring-cloud-gcp.version>
        <spring-cloud.version>2020.0.4</spring-cloud.version>
        <java.version>11</java.version>
```

```shell
2021-10-07 15:18:05.334 ERROR 3524350 --- [main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pubSubHealthContributor' defined in class path resource [com/google/cloud/spring/autoconfigure/pubsub/health/PubSubHealthIndicatorAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.health.HealthContributor]: Factory method 'pubSubHealthContributor' threw exception; nested exception is org.springframework.beans.factory.BeanInitializationException: Validation of health indicator failed; nested exception is java.util.concurrent.TimeoutException
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:771)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:763)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:438)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:339)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1318)
	at com.fastlane.billview.BillviewMainApplication.main(BillviewMainApplication.java:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.health.HealthContributor]: Factory method 'pubSubHealthContributor' threw exception; nested exception is org.springframework.beans.factory.BeanInitializationException: Validation of health indicator failed; nested exception is java.util.concurrent.TimeoutException
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 28 common frames omitted
Caused by: org.springframework.beans.factory.BeanInitializationException: Validation of health indicator failed; nested exception is java.util.concurrent.TimeoutException
	at com.google.cloud.spring.autoconfigure.pubsub.health.PubSubHealthIndicator.validationFailed(PubSubHealthIndicator.java:169)
	at com.google.cloud.spring.autoconfigure.pubsub.health.PubSubHealthIndicator.doHealthCheck(PubSubHealthIndicator.java:139)
	at com.google.cloud.spring.autoconfigure.pubsub.health.PubSubHealthIndicator.validateHealthCheck(PubSubHealthIndicator.java:106)
	at com.google.cloud.spring.autoconfigure.pubsub.health.PubSubHealthIndicatorAutoConfiguration.createIndicator(PubSubHealthIndicatorAutoConfiguration.java:79)
	at com.google.cloud.spring.autoconfigure.pubsub.health.PubSubHealthIndicatorAutoConfiguration.createIndicator(PubSubHealthIndicatorAutoConfiguration.java:49)
	at org.springframework.boot.actuate.autoconfigure.health.AbstractCompositeHealthContributorConfiguration.createContributor(AbstractCompositeHealthContributorConfiguration.java:54)
	at com.google.cloud.spring.autoconfigure.pubsub.health.PubSubHealthIndicatorAutoConfiguration.pubSubHealthContributor(PubSubHealthIndicatorAutoConfiguration.java:69)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 29 common frames omitted
Caused by: java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at org.springframework.util.concurrent.SettableListenableFuture.get(SettableListenableFuture.java:134)
	at com.google.cloud.spring.autoconfigure.pubsub.health.PubSubHealthIndicator.pullMessage(PubSubHealthIndicator.java:148)
	at com.google.cloud.spring.autoconfigure.pubsub.health.PubSubHealthIndicator.doHealthCheck(PubSubHealthIndicator.java:122)

```

**Comment by elefeint** [comment]
@michaelmok2021 Like @suztomo asked, is this a regression? Did this work for you in the past with different versions / on different enviornments? Does this only happen when the volume of pent-up messages is high?

Additionally, try increasing `spring.cloud.gcp.pubsub.health.timeout-millis` value -- the default is 2 seconds ([details in docs](https://googlecloudplatform.github.io/spring-cloud-gcp/2.0.4/reference/html/index.html#cloud-pubsub-health-indicator)).

**Comment by michaelmok2021** [comment]
@elefeint , hmm we stop the appl and start the app again on Ubuntu Server 20.0.4, Open JDK 11 and it works. Still keen to figure out the cause. Looks like a timing, race condition issue....

**Comment by elefeint** [comment]
@michaelmok2021 Definitely try setting `spring.cloud.gcp.pubsub.health.timeout-millis` higher though -- to 4-5 seconds, and see if the issue can still be reproduced in the failed scenario.

**Comment by itsliang** [comment]
```
plugins {
    id 'org.springframework.boot' version '2.5.6'
    id 'io.spring.dependency-management' version '1.0.11.RELEASE'
}

dependencyManagement {
    imports {
        mavenBom 'com.google.cloud:spring-cloud-gcp-dependencies:2.0.5'
    }
}
```

Worked on my Debian 10 Linux, JDK 11, `spring.cloud.gcp.pubsub.health.timeout-millis=2000`.

Failed on my macOS 10.15.7, JDK 11, `spring.cloud.gcp.pubsub.health.timeout-millis=5000`.

Worked on my macOS 10.15.7, JDK 11, `spring.cloud.gcp.pubsub.health.timeout-millis=10000`.

**Comment by elefeint** [comment]
@itsliang This is also on startup with "Validation of health indicator failed" exception, right? Not just during regular operation?

**Comment by tadas-subonis** [comment]
How can I disable this entirely?

**Comment by tadas-subonis** [comment]
```
management.health.pubsub.enabled=false
```

**Comment by itsliang** [comment]
@elefeint Yes, it happened on startup with "Validation of health indicator failed" exception. I didn't test it further, so I don't know if it will failed during regular operation.

**Comment by elefeint** [comment]
Thanks! We'll remove the startup check in a future release.

**Comment by michalstefanext** [comment]
@elefeint By saying "We'll remove the startup check in a future release.", you mean there will be no connectivity check during startup in future release or it means something else? Thanks.

**Comment by elefeint** [comment]
Yes; we should not be preventing application startup on healthcheck failure, especially since we are seeing false positive failures. That's a higher level decision that should be up to each individual application.

**Comment by saravg2012** [comment]
> ```shell
> org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pubSubHealthContributor' defined in class path resource [com/google/cloud/spring/autoconfigure/pubsub/health/PubSubHealthIndicatorAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.health.HealthContributor]: Factory method 'pubSubHealthContributor' threw exception; nested exception is org.springframework.beans.factory.BeanInitializationException: Validation of health indicator failed; nested exception is java.util.concurrent.TimeoutException
> 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
> 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
> ```

Correct Answer

**Comment by saravg2012** [comment]
> ```
> management.health.pubsub.enabled=false
> ```

YES. Correct answer is : management.health.pubsub.enabled=false
