### ISSUE TITLE
[Spring Cloud Datastore] Can't read Blob type into byte[] using Repository and Entity

### ISSUE THREAD

**Issue by esmuellert** [GoogleCloudPlatform/spring-cloud-gcp#661]
**Describe the bug**
Please provide details of the problem, including the version of Spring Cloud that you
are using. 

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.5.5</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>xxxxxxxxxxx</groupId>
    <artifactId>xxxxxxxx</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>backend</name>
    <description>xxxxxxxxxxxxxxxxxx</description>

    <properties>
        <java.version>1.8</java.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.google.cloud</groupId>
                <artifactId>spring-cloud-gcp-dependencies</artifactId>
                <version>2.0.4</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-rest</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <scope>runtime</scope>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.junit.vintage</groupId>
                    <artifactId>junit-vintage-engine</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.auth0</groupId>
            <artifactId>java-jwt</artifactId>
            <version>3.10.3</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
            <version>2.3.3.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk</artifactId>
            <version>1.11.918</version>
        </dependency>
        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>spring-cloud-gcp-starter-data-datastore</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
```
I have an entity of Admin:

```
@Entity
public class Admin implements Role {
    @Id
    Key key;
    private UUID id;
    private String username;
    private String password;
    private LocalDateTime tokenExpired;
    private byte[] tokenSecret;
}

```
And the following AdminRepository:

```
public interface AdminRepository extends DatastoreRepository<Admin, Key> {
    Optional<Admin> findOneByUsername(String username);
}
```

At first, I tried to save the entity to Datastore using `adminRepository.save(admin)`, it was fine and a record was generated in the database. The `byte[]` type was automatically converted to `Blob`. However, when I called `adminRepository.findOneByUsername(username)` to get the record I previously inserted, it always throughs an exception.

```
Caused by: com.google.cloud.spring.data.datastore.core.mapping.DatastoreDataException: Unable to read property tokenSecret; nested exception is org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [com.google.cloud.datastore.Blob] to type [java.lang.Byte]
	at com.google.cloud.spring.data.datastore.core.convert.EntityPropertyValueProvider.getPropertyValue(EntityPropertyValueProvider.java:75)
	at com.google.cloud.spring.data.datastore.core.convert.EntityPropertyValueProvider.getPropertyValue(EntityPropertyValueProvider.java:59)
	at com.google.cloud.spring.data.datastore.core.convert.DefaultDatastoreEntityConverter.lambda$read$0(DefaultDatastoreEntityConverter.java:170)
	at com.google.cloud.spring.data.datastore.core.mapping.DatastorePersistentEntityImpl.lambda$doWithColumnBackedProperties$0(DatastorePersistentEntityImpl.java:206)
	at org.springframework.data.mapping.model.BasicPersistentEntity.doWithProperties(BasicPersistentEntity.java:360)
	at com.google.cloud.spring.data.datastore.core.mapping.DatastorePersistentEntityImpl.doWithColumnBackedProperties(DatastorePersistentEntityImpl.java:203)
	at com.google.cloud.spring.data.datastore.core.convert.DefaultDatastoreEntityConverter.read(DefaultDatastoreEntityConverter.java:166)
	... 67 more
Caused by: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [com.google.cloud.datastore.Blob] to type [java.lang.Byte]
	at org.springframework.core.convert.support.GenericConversionService.handleConverterNotFound(GenericConversionService.java:322)
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:195)
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:175)
	at com.google.cloud.spring.data.datastore.core.convert.TwoStepsConversions.convertOnReadSingle(TwoStepsConversions.java:220)
	at com.google.cloud.spring.data.datastore.core.convert.TwoStepsConversions.convertOnRead(TwoStepsConversions.java:178)
	at com.google.cloud.spring.data.datastore.core.convert.TwoStepsConversions.convertOnRead(TwoStepsConversions.java:130)
	at com.google.cloud.spring.data.datastore.core.convert.EntityPropertyValueProvider.getPropertyValue(EntityPropertyValueProvider.java:71)
	... 73 more
```
 It seems that the `Blob` object can't be converted back to `byte[]` here. However, the document of ` 14.2.5. Supported Types` said that the `byte[]` is supported in Datastore. It should be successfully converted. Also, the error message said that `Blob` can't be converted to `Byte`. However, the type defined in my entity is `byte[]`, which is very confusing. I am very appreciated if someone can help me with this issue.

**Comment by ddixit14** [comment]
Hi @esmuellert, if you need to store a byte[] array in Datastore, you need to store them as either short byte string or long byte string. Please refer to the following links as to how you can convert your byte[] array to these two data types :

1. com.google.appengine.api.datastore.ShortBlob : short byte string, < 500 bytes : [Short Blob Conversion](https://cloud.google.com/appengine/docs/standard/java/javadoc/com/google/appengine/api/datastore/ShortBlob.html#ShortBlob-byte:A-)
2. com.google.appengine.api.datastore.Blob: long byte string (not orderable) : [Blob Conversion](https://cloud.google.com/appengine/docs/standard/java/javadoc/com/google/appengine/api/datastore/ShortBlob.html#ShortBlob-byte:A-)

**Comment by elefeint** [comment]
Right, this can be done manually, but byte array to blob and back should be a conversion that we [support automatically](https://googlecloudplatform.github.io/spring-cloud-gcp/2.0.4/reference/html/index.html#supported-types-2). 
Re-opening for additional investigation.

**Comment by elefeint** [comment]
Looks like an underimplemented feature. Validated by modifying `DefaultDatastoreEntityConverterTests.readTest()` to add `.set("byteArrayField", Blob.copyFrom(bytes))` to the Datastore entity.
