### ISSUE TITLE
Incorrect Spanner custom converter used

### ISSUE THREAD

**Issue by guycall** [GoogleCloudPlatform/spring-cloud-gcp#767]
I am experimenting to determine if there is any performance difference between BYTES(16) and STRING(36) for UUID primary keys. But I get an unexpected result where the incorrect custom converter gets used.

I made a new sample project with Spring Initializr (Spring Boot 2.6.1, Gradle, Java 11) and version 2.0.6 of spring-cloud-gcp-starter-data-spanner.

Created custom converters for ByteArray <-> UUID and String <-> UUID: 

```
import com.google.cloud.ByteArray;
import com.google.cloud.spring.data.spanner.core.convert.ConverterAwareMappingSpannerEntityProcessor;
import com.google.cloud.spring.data.spanner.core.convert.SpannerEntityProcessor;
import com.google.cloud.spring.data.spanner.core.mapping.SpannerMappingContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.convert.converter.Converter;

import javax.annotation.Nullable;
import java.nio.ByteBuffer;
import java.util.Arrays;
import java.util.UUID;

@Configuration
class SpannerConverterConfig {

    @Bean
    public SpannerEntityProcessor spannerEntityProcessor(SpannerMappingContext mappingContext) {
        return new ConverterAwareMappingSpannerEntityProcessor(mappingContext,
                Arrays.asList(UUID_TO_SPANNER_BYTES, UUID_TO_SPANNER_STRING),
                Arrays.asList(SPANNER_BYTES_TO_UUID, SPANNER_STRING_TO_UUID));
    }

    public static final Converter<UUID, ByteArray> UUID_TO_SPANNER_BYTES =
        new Converter<UUID, ByteArray>() {
            @Nullable
            @Override
            public ByteArray convert(UUID source) {
                var bytes = new byte[16];
                var buffer = ByteBuffer.wrap(bytes);
                buffer.putLong(source.getMostSignificantBits());
                buffer.putLong(source.getLeastSignificantBits());
                var byteArray = ByteArray.copyFrom(buffer.array());
                return byteArray;
            }
        };

    public static final Converter<ByteArray, UUID> SPANNER_BYTES_TO_UUID =
        new Converter<ByteArray, UUID>() {
            @Nullable
            @Override
            public UUID convert(ByteArray source) {
                ByteBuffer byteBuffer = ByteBuffer.wrap(source.toByteArray());
                var high = byteBuffer.getLong();
                var low = byteBuffer.getLong();
                return new UUID(high, low);
            }
        };

    public static final Converter<UUID, String> UUID_TO_SPANNER_STRING =
        new Converter<UUID, String>() {
            @Nullable
            @Override
            public String convert(UUID source) {
                return source.toString();
            }
        };

    public static final Converter<String, UUID> SPANNER_STRING_TO_UUID =
        new Converter<String, UUID>() {
            @Nullable
            @Override
            public UUID convert(String source) {
                return UUID.fromString(source);
            }
        };
}
```

I created two simple tables. One with the primary key as a BYTES(16) and one as STRING(36). Then created the corresponding entities and repositories:

```
 CREATE TABLE Strings (
   Id STRING(36) NOT NULL,
   Name STRING(100) NOT NULL,
   Nickname STRING(100),
   Age INT64 NOT NULL,
   Active BOOL NOT NULL,
   UpdatedAt TIMESTAMP NOT NULL,
 ) PRIMARY KEY(Id)
 ```

```
@Table(name="Strings")
public class StringEntity {
    @PrimaryKey
    @Column(name="Id")
    UUID id;
    @Column(name="Name")
    String name;
    @Column(name="Nickname")
    String nickname;
    @Column(name="Age")
    Integer age;
    @Column(name="Active")
    Boolean active;
    @Column(name="UpdatedAt")
    Timestamp updatedAt;
}
```

```
@Repository
public interface StringRepository extends SpannerRepository<StringEntity, UUID> {
}
```

I created some simple test code that creates an entity with a random primary key (`UUID.randomUUID()`) then  saves it with repositories `save` method, then finally tries to find again with `findById`.

This works as expected for the BYTES(16) table. But for the STRING(36) I get the error:

```
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [java.util.UUID] for value 'Lc9TK9OsSTWMgoaAEwwdRw=='; nested exception is java.lang.IllegalArgumentException: Invalid UUID string: Lc9TK9OsSTWMgoaAEwwdRw==] with root cause
java.lang.IllegalArgumentException: Invalid UUID string: Lc9TK9OsSTWMgoaAEwwdRw==
	at java.base/java.util.UUID.fromString(UUID.java:215) ~[na:na]
	at com.example.demo.SpannerConverterConfig$4.convert(SpannerConverterConfig.java:66) ~[main/:na]
	at com.example.demo.SpannerConverterConfig$4.convert(SpannerConverterConfig.java:62) ~[main/:na]
```

When I step through the code I can see UUID_TO_SPANNER_BYTES converter is incorrectly used during the `save` and `findById` methods, but the mapping of the fetched data to my entity uses the correct SPANNER_STRING_TO_UUID converter. This throws the error.

If I remove the UUID_TO_SPANNER_BYTES and SPANNER_BYTES_TO_UUID converters then STRING(36) works as expected.

**Comment by suztomo** [comment]
It seems that your observe that ConverterAwareMappingSpannerEntityProcessor is not working correctly. Let me troubleshoot further.

**Comment by suztomo** [comment]
@guycall I need your help in clarification.

1. When you save the data, do you see the UUID data is stored correctly with expected types,  `BYTES(16)` and one as `STRING(36)`?

(If not, then the next question below is less important)

2. When you read the data, do you see the Spanner Byte data and Spanner String data are read correctly?

**Comment by suztomo** [comment]
It turned out that `ConverterAwareMappingSpannerEntityProcessor ` cannot have duplicate converters. We'll enrich document to explain this.

**Comment by guycall** [comment]
Thank you for the quick response.
