### ISSUE TITLE
Spring Boot 2.5.8 graceful shutdown - java.util.concurrent.RejectedExecutionException

### ISSUE THREAD

**Issue by michalstefanext** [GoogleCloudPlatform/spring-cloud-gcp#956]
I am not 100% sure if this is an issue, but every time I shutdown the spring boot application (version 2.5.8) using:

- spring.cloud.gcp.pubsub v3.1.0
- having subscriber using PubSubInboundChannelAdapter (spring integration)
- using server.shutdown=graceful for spring boot app

I get this exception from Subscriber:

```
Exception in thread "Thread-35" java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3d8416eb[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@705df4f2[Wrapped task = com.google.common.util.concurrent.ListenerCallQueue$PerListenerQueue@5de316dd]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@54d338fa[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2065)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:705)
	at com.google.common.util.concurrent.ListenerCallQueue$PerListenerQueue.dispatch(ListenerCallQueue.java:170)
	at com.google.common.util.concurrent.ListenerCallQueue.dispatch(ListenerCallQueue.java:121)
	at com.google.common.util.concurrent.AbstractService.dispatchListenerEvents(AbstractService.java:516)
	at com.google.common.util.concurrent.AbstractService.notifyFailed(AbstractService.java:479)
	at com.google.api.core.AbstractApiService$InnerService.innerNotifyFailed(AbstractApiService.java:165)
	at com.google.api.core.AbstractApiService$InnerService.access$400(AbstractApiService.java:145)
	at com.google.api.core.AbstractApiService.notifyFailed(AbstractApiService.java:142)
	at com.google.cloud.pubsub.v1.Subscriber.access$1900(Subscriber.java:91)
	at com.google.cloud.pubsub.v1.Subscriber$2.run(Subscriber.java:303)
	at java.base/java.lang.Thread.run(Thread.java:833)

Process finished with exit code 130
```

Is there a way how to make it shutdown gracefully without exception please?

**Comment by elefeint** [comment]
`RejectedExecutionException` means the threadpool is in the process of gracefully shutting down, but was asked to do additional work, and firmly said no.

On the one hand, this is not a problem because it's a normal scenario -- a Pub/Sub message is trying to come in from a gRPC stream. On the other hand, we should probably try to shut down the adapter before the thread pool itself closes to avoid cluttering your logs with exceptions.

**Comment by meltsufin** [comment]
Thanks for the update! Would you be able to provide some sample code that reproduces this error? Thanks!

**Comment by michalstefanext** [comment]
Apologies @meltsufin, we've switched from spring-integration to use spring-cloud-gcp-pubsub directly, so we're no longer facing this issue + we have removed the branch with previous spring-integration code, so I believe it will be better to close this issue, but thanks for your help!

**Comment by deven-kumar** [comment]
@elefeint this issue still exist for subscriber are created with `spring-cloud-gcp-pubsub-stream-binder`

```
at java.base/java.lang.Thread.run(Unknown Source)
at com.google.cloud.pubsub.v1.Subscriber$2.run(Subscriber.java:375)
at com.google.cloud.pubsub.v1.Subscriber.access$2700(Subscriber.java:95)
at com.google.api.core.AbstractApiService.notifyFailed(AbstractApiService.java:141)
at com.google.api.core.AbstractApiService$InnerService.access$400(AbstractApiService.java:144)
at com.google.api.core.AbstractApiService$InnerService.innerNotifyFailed(AbstractApiService.java:164)
at com.google.common.util.concurrent.AbstractService.notifyFailed(AbstractService.java:485)
at com.google.common.util.concurrent.AbstractService.dispatchListenerEvents(AbstractService.java:526)
at com.google.common.util.concurrent.ListenerCallQueue.dispatch(ListenerCallQueue.java:121)
at com.google.common.util.concurrent.ListenerCallQueue$PerListenerQueue.dispatch(ListenerCallQueue.java:171)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.execute(Unknown Source)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
Exception in thread "Thread-25" java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@16ff5793[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@29ee6219[Wrapped task = com.google.common.util.concurrent.ListenerCallQueue$PerListenerQueue@586e46b2]] rejected from org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler$1@6dc9e869[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]

```



We are using version `8.0.4` of `spring-cloud-gcp-pubsub` and `spring-cloud-gcp-pubsub-stream-binder` along with spring boot 4.

These error are not impacting us but these are noise and polluting logs during application restart.

We are using `spring-cloud-gcp-pubsub-stream-binder` for consumers (via Spring Cloud Stream) and there are multiple consumer like this
```
spring.cloud.function.definition: eventWrapperConsumer;processorDataConsumer
spring.cloud.stream.bindings:
  eventWrapperConsumer-in-0: ...
  processorDataConsumer-in-0: ...
```

The binder internally creates PubSubInboundChannelAdapter that manages the Subscriber instances. the bug seems here in PubSubInboundChannelAdapter.doStop():

```
@Override
protected void doStop() {
    if (this.subscriber != null) {
        this.subscriber.stopAsync();   // ← FIRE AND FORGET! No await!
    }
    super.doStop();
}
```

The method returns instantly, Spring continues shutting down other beans, and eventually the scheduler terminates. Meanwhile, the subscriber's internal thread is still cleaning up:

```
// Google Cloud Subscriber.doStop() — runs on its own thread
protected void doStop() {
    new Thread(() -> {
        runShutdown();    // awaits streaming connections
        notifyStopped();  // ← this triggers notifyFailed() → ListenerCallQueue → REJECTED
    }).start();
}
```

I think there need to be `subscriber.stopAsync().awaitTerminated();` in `PubSubInboundChannelAdapter.doStop():` as per `Subscriber` documentation.
https://docs.cloud.google.com/java/docs/reference/google-cloud-pubsub/latest/com.google.cloud.pubsub.v1.Subscriber#com_google_cloud_pubsub_v1_Subscriber_startAsync__
